language: c
compiler: 
  - gcc
  - clang
branches:
  except:
    - c
env:
  - VALAV="0.24"
  - VALAV="0.22"
  - VALAV="0.20"
  - VALAV="0.18"
  - VALAV="0.16"
  - VALAV="0.14"

matrix:
  fast_finish: true
  allow_failures:
    - env: VALAV="0.14"
    - env: VALAV="0.16"
    - compiler: clang

before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common libglib2.0-dev libvala-$VALAV-dev valac-$VALAV gobject-introspection libgee-dev
script:
  - cmake .
  - make
notifications:
  irc: "sterling.notroll.me#yrcd"
