/* channel.c generated by valac 0.24.0, the Vala compiler
 * generated from channel.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_YRCD_CHANNEL (yrcd_yrcd_channel_get_type ())
#define YRCD_YRCD_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channel))
#define YRCD_YRCD_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channelClass))
#define YRCD_IS_YRCD_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_CHANNEL))
#define YRCD_IS_YRCD_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_CHANNEL))
#define YRCD_YRCD_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channelClass))

typedef struct _yrcdyrcd_channel yrcdyrcd_channel;
typedef struct _yrcdyrcd_channelClass yrcdyrcd_channelClass;
typedef struct _yrcdyrcd_channelPrivate yrcdyrcd_channelPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _yrcdyrcd_channel {
	GObject parent_instance;
	yrcdyrcd_channelPrivate * priv;
	gchar* name;
	gchar** modes;
	gint modes_length1;
	gint _modes_size_;
};

struct _yrcdyrcd_channelClass {
	GObjectClass parent_class;
};


static gpointer yrcd_yrcd_channel_parent_class = NULL;

GType yrcd_yrcd_channel_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_YRCD_CHANNEL_DUMMY_PROPERTY
};
yrcdyrcd_channel* yrcd_yrcd_channel_new (void);
yrcdyrcd_channel* yrcd_yrcd_channel_construct (GType object_type);
static void yrcd_yrcd_channel_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


yrcdyrcd_channel* yrcd_yrcd_channel_construct (GType object_type) {
	yrcdyrcd_channel * self = NULL;
	self = (yrcdyrcd_channel*) g_object_new (object_type, NULL);
	return self;
}


yrcdyrcd_channel* yrcd_yrcd_channel_new (void) {
	return yrcd_yrcd_channel_construct (YRCD_TYPE_YRCD_CHANNEL);
}


static void yrcd_yrcd_channel_class_init (yrcdyrcd_channelClass * klass) {
	yrcd_yrcd_channel_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_channel_finalize;
}


static void yrcd_yrcd_channel_instance_init (yrcdyrcd_channel * self) {
}


static void yrcd_yrcd_channel_finalize (GObject* obj) {
	yrcdyrcd_channel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channel);
	_g_free0 (self->name);
	self->modes = (_vala_array_free (self->modes, self->modes_length1, (GDestroyNotify) g_free), NULL);
	G_OBJECT_CLASS (yrcd_yrcd_channel_parent_class)->finalize (obj);
}


GType yrcd_yrcd_channel_get_type (void) {
	static volatile gsize yrcd_yrcd_channel_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_channel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_channelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_channel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_channel), 0, (GInstanceInitFunc) yrcd_yrcd_channel_instance_init, NULL };
		GType yrcd_yrcd_channel_type_id;
		yrcd_yrcd_channel_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_channel", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_channel_type_id__volatile, yrcd_yrcd_channel_type_id);
	}
	return yrcd_yrcd_channel_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



