/* config.c generated by valac 0.24.0, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>


#define YRCD_TYPE_YRCD_CONFIG (yrcd_yrcd_config_get_type ())
#define YRCD_YRCD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_config))
#define YRCD_YRCD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_configClass))
#define YRCD_IS_YRCD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_CONFIG))
#define YRCD_IS_YRCD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_CONFIG))
#define YRCD_YRCD_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_configClass))

typedef struct _yrcdyrcd_config yrcdyrcd_config;
typedef struct _yrcdyrcd_configClass yrcdyrcd_configClass;
typedef struct _yrcdyrcd_configPrivate yrcdyrcd_configPrivate;
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _yrcdyrcd_config {
	GObject parent_instance;
	yrcdyrcd_configPrivate * priv;
	GList* listen_ports;
	gchar** listen_ips;
	gint listen_ips_length1;
	GList* motd;
	gint ping_invertal;
	gboolean config_error;
	gchar* salt;
};

struct _yrcdyrcd_configClass {
	GObjectClass parent_class;
};

struct _yrcdyrcd_configPrivate {
	GKeyFile* file;
	gchar* _sname;
};


static gpointer yrcd_yrcd_config_parent_class = NULL;

GType yrcd_yrcd_config_get_type (void) G_GNUC_CONST;
#define YRCD_YRCD_CONFIG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_configPrivate))
enum  {
	YRCD_YRCD_CONFIG_DUMMY_PROPERTY,
	YRCD_YRCD_CONFIG_SNAME
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
yrcdyrcd_config* yrcd_yrcd_config_new (const gchar* filepath);
yrcdyrcd_config* yrcd_yrcd_config_construct (GType object_type, const gchar* filepath);
void yrcd_yrcd_config_set_sname (yrcdyrcd_config* self, const gchar* value);
const gchar* yrcd_yrcd_config_get_sname (yrcdyrcd_config* self);
static void yrcd_yrcd_config_finalize (GObject* obj);
static void _vala_yrcd_yrcd_config_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_yrcd_yrcd_config_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


yrcdyrcd_config* yrcd_yrcd_config_construct (GType object_type, const gchar* filepath) {
	yrcdyrcd_config * self = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (filepath != NULL, NULL);
	self = (yrcdyrcd_config*) g_object_new (object_type, NULL);
	{
		GKeyFile* _tmp0_ = NULL;
		const gchar* _tmp1_ = NULL;
		GKeyFile* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		GKeyFile* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gint* tmplist = NULL;
		GKeyFile* _tmp6_ = NULL;
		gsize _tmp7_;
		gint* _tmp8_ = NULL;
		gint tmplist_length1 = 0;
		gint _tmplist_size_ = 0;
		gint* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gchar** _tmp15_ = NULL;
		GKeyFile* _tmp16_ = NULL;
		gsize _tmp17_;
		gchar** _tmp18_ = NULL;
		gint _tmp15__length1 = 0;
		gint __tmp15__size_ = 0;
		gchar** _tmp19_ = NULL;
		gint _tmp19__length1 = 0;
		gchar* motdpath = NULL;
		GKeyFile* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		GFile* motdfile = NULL;
		const gchar* _tmp22_ = NULL;
		GFile* _tmp23_ = NULL;
		GFileInputStream* _tmp24_ = NULL;
		GFile* _tmp25_ = NULL;
		GFileInputStream* _tmp26_ = NULL;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp27_ = NULL;
		gchar* motd_line = NULL;
		gint _tmp35_ = 0;
		GKeyFile* _tmp36_ = NULL;
		gint _tmp37_ = 0;
		gchar* _tmp38_ = NULL;
		GKeyFile* _tmp39_ = NULL;
		gchar* _tmp40_ = NULL;
		gchar* _tmp41_ = NULL;
		_tmp0_ = self->priv->file;
		_tmp1_ = filepath;
		g_key_file_load_from_file (_tmp0_, _tmp1_, G_KEY_FILE_NONE, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_tmp2_ = self->priv->file;
		g_key_file_set_list_separator (_tmp2_, ',');
		_tmp4_ = self->priv->file;
		_tmp5_ = g_key_file_get_string (_tmp4_, "ServerVariables", "server_name", &_inner_error_);
		_tmp3_ = _tmp5_;
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		yrcd_yrcd_config_set_sname (self, _tmp3_);
		_tmp6_ = self->priv->file;
		_tmp8_ = g_key_file_get_integer_list (_tmp6_, "Networking", "listening_ports", &_tmp7_, &_inner_error_);
		tmplist = _tmp8_;
		tmplist_length1 = _tmp7_;
		_tmplist_size_ = tmplist_length1;
		if (_inner_error_ != NULL) {
			_g_free0 (_tmp3_);
			goto __catch0_g_error;
		}
		_tmp9_ = tmplist;
		_tmp9__length1 = tmplist_length1;
		{
			gint* k_collection = NULL;
			gint k_collection_length1 = 0;
			gint _k_collection_size_ = 0;
			gint k_it = 0;
			k_collection = _tmp9_;
			k_collection_length1 = _tmp9__length1;
			for (k_it = 0; k_it < _tmp9__length1; k_it = k_it + 1) {
				gint k = 0;
				k = k_collection[k_it];
				{
					guint16 j = 0U;
					guint16 _tmp14_ = 0U;
					{
						gboolean _tmp10_ = FALSE;
						j = (guint16) 0;
						_tmp10_ = TRUE;
						while (TRUE) {
							guint16 _tmp11_ = 0U;
							gint _tmp12_ = 0;
							guint16 _tmp13_ = 0U;
							if (!_tmp10_) {
							}
							_tmp10_ = FALSE;
							_tmp11_ = j;
							_tmp12_ = k;
							if (!(((gint) _tmp11_) < _tmp12_)) {
								break;
							}
							_tmp13_ = j;
							j = _tmp13_ + 1;
						}
					}
					_tmp14_ = j;
					self->listen_ports = g_list_append (self->listen_ports, (gpointer) ((guintptr) _tmp14_));
				}
			}
		}
		_tmp16_ = self->priv->file;
		_tmp18_ = g_key_file_get_string_list (_tmp16_, "Networking", "listening_ips", &_tmp17_, &_inner_error_);
		_tmp15_ = _tmp18_;
		_tmp15__length1 = _tmp17_;
		__tmp15__size_ = _tmp15__length1;
		if (_inner_error_ != NULL) {
			tmplist = (g_free (tmplist), NULL);
			_g_free0 (_tmp3_);
			goto __catch0_g_error;
		}
		_tmp19_ = _tmp15_;
		_tmp19__length1 = _tmp15__length1;
		_tmp15_ = NULL;
		_tmp15__length1 = 0;
		self->listen_ips = (_vala_array_free (self->listen_ips, self->listen_ips_length1, (GDestroyNotify) g_free), NULL);
		self->listen_ips = _tmp19_;
		self->listen_ips_length1 = _tmp19__length1;
		_tmp20_ = self->priv->file;
		_tmp21_ = g_key_file_get_string (_tmp20_, "ServerVariables", "motd_path", &_inner_error_);
		motdpath = _tmp21_;
		if (_inner_error_ != NULL) {
			_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
			tmplist = (g_free (tmplist), NULL);
			_g_free0 (_tmp3_);
			goto __catch0_g_error;
		}
		_tmp22_ = motdpath;
		_tmp23_ = g_file_new_for_path (_tmp22_);
		motdfile = _tmp23_;
		_tmp25_ = motdfile;
		_tmp26_ = g_file_read (_tmp25_, NULL, &_inner_error_);
		_tmp24_ = _tmp26_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (motdfile);
			_g_free0 (motdpath);
			_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
			tmplist = (g_free (tmplist), NULL);
			_g_free0 (_tmp3_);
			goto __catch0_g_error;
		}
		_tmp27_ = g_data_input_stream_new ((GInputStream*) _tmp24_);
		dis = _tmp27_;
		while (TRUE) {
			gchar* _tmp28_ = NULL;
			GDataInputStream* _tmp29_ = NULL;
			gchar* _tmp30_ = NULL;
			gchar* _tmp31_ = NULL;
			const gchar* _tmp32_ = NULL;
			const gchar* _tmp33_ = NULL;
			gchar* _tmp34_ = NULL;
			_tmp29_ = dis;
			_tmp30_ = g_data_input_stream_read_line (_tmp29_, NULL, NULL, &_inner_error_);
			_tmp28_ = _tmp30_;
			if (_inner_error_ != NULL) {
				_g_free0 (motd_line);
				_g_object_unref0 (dis);
				_g_object_unref0 (_tmp24_);
				_g_object_unref0 (motdfile);
				_g_free0 (motdpath);
				_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
				tmplist = (g_free (tmplist), NULL);
				_g_free0 (_tmp3_);
				goto __catch0_g_error;
			}
			_tmp31_ = _tmp28_;
			_tmp28_ = NULL;
			_g_free0 (motd_line);
			motd_line = _tmp31_;
			_tmp32_ = motd_line;
			if (!(_tmp32_ != NULL)) {
				_g_free0 (_tmp28_);
				break;
			}
			_tmp33_ = motd_line;
			_tmp34_ = g_strdup (_tmp33_);
			self->motd = g_list_append (self->motd, _tmp34_);
			_g_free0 (_tmp28_);
		}
		_tmp36_ = self->priv->file;
		_tmp37_ = g_key_file_get_integer (_tmp36_, "ServerVariables", "ping_invertal", &_inner_error_);
		_tmp35_ = _tmp37_;
		if (_inner_error_ != NULL) {
			_g_free0 (motd_line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp24_);
			_g_object_unref0 (motdfile);
			_g_free0 (motdpath);
			_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
			tmplist = (g_free (tmplist), NULL);
			_g_free0 (_tmp3_);
			goto __catch0_g_error;
		}
		self->ping_invertal = _tmp35_;
		_tmp39_ = self->priv->file;
		_tmp40_ = g_key_file_get_string (_tmp39_, "ServerVariables", "host_salt", &_inner_error_);
		_tmp38_ = _tmp40_;
		if (_inner_error_ != NULL) {
			_g_free0 (motd_line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp24_);
			_g_object_unref0 (motdfile);
			_g_free0 (motdpath);
			_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
			tmplist = (g_free (tmplist), NULL);
			_g_free0 (_tmp3_);
			goto __catch0_g_error;
		}
		_tmp41_ = _tmp38_;
		_tmp38_ = NULL;
		_g_free0 (self->salt);
		self->salt = _tmp41_;
		_g_free0 (_tmp38_);
		_g_free0 (motd_line);
		_g_object_unref0 (dis);
		_g_object_unref0 (_tmp24_);
		_g_object_unref0 (motdfile);
		_g_free0 (motdpath);
		_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
		tmplist = (g_free (tmplist), NULL);
		_g_free0 (_tmp3_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp42_ = NULL;
		GError* _tmp43_ = NULL;
		const gchar* _tmp44_ = NULL;
		gchar* _tmp45_ = NULL;
		gchar* _tmp46_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp42_ = stdout;
		_tmp43_ = e;
		_tmp44_ = _tmp43_->message;
		_tmp45_ = g_strdup_printf ("Error Loading config file: %s\n", _tmp44_);
		_tmp46_ = _tmp45_;
		fprintf (_tmp42_, "%s", _tmp46_);
		_g_free0 (_tmp46_);
		self->config_error = TRUE;
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


yrcdyrcd_config* yrcd_yrcd_config_new (const gchar* filepath) {
	return yrcd_yrcd_config_construct (YRCD_TYPE_YRCD_CONFIG, filepath);
}


const gchar* yrcd_yrcd_config_get_sname (yrcdyrcd_config* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_sname;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_config_set_sname (yrcdyrcd_config* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_sname);
	self->priv->_sname = _tmp1_;
	g_object_notify ((GObject *) self, "sname");
}


static void yrcd_yrcd_config_class_init (yrcdyrcd_configClass * klass) {
	yrcd_yrcd_config_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (yrcdyrcd_configPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_yrcd_yrcd_config_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_yrcd_yrcd_config_set_property;
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_config_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_CONFIG_SNAME, g_param_spec_string ("sname", "sname", "sname", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void yrcd_yrcd_config_instance_init (yrcdyrcd_config * self) {
	GKeyFile* _tmp0_ = NULL;
	self->priv = YRCD_YRCD_CONFIG_GET_PRIVATE (self);
	_tmp0_ = g_key_file_new ();
	self->priv->file = _tmp0_;
	self->config_error = FALSE;
}


static void yrcd_yrcd_config_finalize (GObject* obj) {
	yrcdyrcd_config * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_config);
	_g_key_file_free0 (self->priv->file);
	_g_free0 (self->priv->_sname);
	_g_list_free0 (self->listen_ports);
	self->listen_ips = (_vala_array_free (self->listen_ips, self->listen_ips_length1, (GDestroyNotify) g_free), NULL);
	__g_list_free__g_free0_0 (self->motd);
	_g_free0 (self->salt);
	G_OBJECT_CLASS (yrcd_yrcd_config_parent_class)->finalize (obj);
}


GType yrcd_yrcd_config_get_type (void) {
	static volatile gsize yrcd_yrcd_config_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_configClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_config), 0, (GInstanceInitFunc) yrcd_yrcd_config_instance_init, NULL };
		GType yrcd_yrcd_config_type_id;
		yrcd_yrcd_config_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_config", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_config_type_id__volatile, yrcd_yrcd_config_type_id);
	}
	return yrcd_yrcd_config_type_id__volatile;
}


static void _vala_yrcd_yrcd_config_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	yrcdyrcd_config * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_config);
	switch (property_id) {
		case YRCD_YRCD_CONFIG_SNAME:
		g_value_set_string (value, yrcd_yrcd_config_get_sname (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_yrcd_yrcd_config_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	yrcdyrcd_config * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_CONFIG, yrcdyrcd_config);
	switch (property_id) {
		case YRCD_YRCD_CONFIG_SNAME:
		yrcd_yrcd_config_set_sname (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



