/* constants.c generated by valac 0.24.0, the Vala compiler
 * generated from constants.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_CONSTANTS (yrcd_constants_get_type ())
#define YRCD_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_CONSTANTS, yrcdConstants))
#define YRCD_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_CONSTANTS, yrcdConstantsClass))
#define YRCD_IS_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_CONSTANTS))
#define YRCD_IS_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_CONSTANTS))
#define YRCD_CONSTANTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_CONSTANTS, yrcdConstantsClass))

typedef struct _yrcdConstants yrcdConstants;
typedef struct _yrcdConstantsClass yrcdConstantsClass;
typedef struct _yrcdConstantsPrivate yrcdConstantsPrivate;

struct _yrcdConstants {
	GObject parent_instance;
	yrcdConstantsPrivate * priv;
};

struct _yrcdConstantsClass {
	GObjectClass parent_class;
};


static gpointer yrcd_constants_parent_class = NULL;

GType yrcd_constants_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_CONSTANTS_DUMMY_PROPERTY
};
#define YRCD_CONSTANTS_version "0.2"
#define YRCD_CONSTANTS_software "yrcd"
yrcdConstants* yrcd_constants_new (void);
yrcdConstants* yrcd_constants_construct (GType object_type);

const gchar* YRCD_CONSTANTS_cmodes[0] = {};
const gchar* YRCD_CONSTANTS_umodes[0] = {};
const gchar* YRCD_CONSTANTS_forbidden_nick_chars[6] = {":", "#", "&", "%", "@", "+"};
const gchar* YRCD_CONSTANTS_chan_prefixes[2] = {"#", "&"};
const gchar* YRCD_CONSTANTS_chan_forbidden[5] = {":", "&", "@", "%", "+"};

yrcdConstants* yrcd_constants_construct (GType object_type) {
	yrcdConstants * self = NULL;
	self = (yrcdConstants*) g_object_new (object_type, NULL);
	return self;
}


yrcdConstants* yrcd_constants_new (void) {
	return yrcd_constants_construct (YRCD_TYPE_CONSTANTS);
}


static void yrcd_constants_class_init (yrcdConstantsClass * klass) {
	yrcd_constants_parent_class = g_type_class_peek_parent (klass);
}


static void yrcd_constants_instance_init (yrcdConstants * self) {
}


GType yrcd_constants_get_type (void) {
	static volatile gsize yrcd_constants_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_constants_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdConstantsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_constants_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdConstants), 0, (GInstanceInitFunc) yrcd_constants_instance_init, NULL };
		GType yrcd_constants_type_id;
		yrcd_constants_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdConstants", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_constants_type_id__volatile, yrcd_constants_type_id);
	}
	return yrcd_constants_type_id__volatile;
}



