/* constants.c generated by valac 0.24.0, the Vala compiler
 * generated from constants.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_YRCD_CONSTANTS (yrcd_yrcd_constants_get_type ())
#define YRCD_YRCD_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_CONSTANTS, yrcdyrcd_constants))
#define YRCD_YRCD_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_CONSTANTS, yrcdyrcd_constantsClass))
#define YRCD_IS_YRCD_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_CONSTANTS))
#define YRCD_IS_YRCD_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_CONSTANTS))
#define YRCD_YRCD_CONSTANTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_CONSTANTS, yrcdyrcd_constantsClass))

typedef struct _yrcdyrcd_constants yrcdyrcd_constants;
typedef struct _yrcdyrcd_constantsClass yrcdyrcd_constantsClass;
typedef struct _yrcdyrcd_constantsPrivate yrcdyrcd_constantsPrivate;

struct _yrcdyrcd_constants {
	GObject parent_instance;
	yrcdyrcd_constantsPrivate * priv;
};

struct _yrcdyrcd_constantsClass {
	GObjectClass parent_class;
};


static gpointer yrcd_yrcd_constants_parent_class = NULL;

GType yrcd_yrcd_constants_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_YRCD_CONSTANTS_DUMMY_PROPERTY
};
#define YRCD_YRCD_CONSTANTS_version "0.1"
#define YRCD_YRCD_CONSTANTS_software "yrcd"
#define YRCD_YRCD_CONSTANTS_motd "Welcome!"
#define YRCD_YRCD_CONSTANTS_sname "test.net.local"
yrcdyrcd_constants* yrcd_yrcd_constants_new (void);
yrcdyrcd_constants* yrcd_yrcd_constants_construct (GType object_type);

const gchar* YRCD_YRCD_CONSTANTS_listen_ips[1] = {"127.0.0.1"};
const guint16 YRCD_YRCD_CONSTANTS_listen_ports[2] = {(guint16) 6667, (guint16) 6668};
const gchar* YRCD_YRCD_CONSTANTS_cmodes[0] = {};
const gchar* YRCD_YRCD_CONSTANTS_umodes[0] = {};

yrcdyrcd_constants* yrcd_yrcd_constants_construct (GType object_type) {
	yrcdyrcd_constants * self = NULL;
	self = (yrcdyrcd_constants*) g_object_new (object_type, NULL);
	return self;
}


yrcdyrcd_constants* yrcd_yrcd_constants_new (void) {
	return yrcd_yrcd_constants_construct (YRCD_TYPE_YRCD_CONSTANTS);
}


static void yrcd_yrcd_constants_class_init (yrcdyrcd_constantsClass * klass) {
	yrcd_yrcd_constants_parent_class = g_type_class_peek_parent (klass);
}


static void yrcd_yrcd_constants_instance_init (yrcdyrcd_constants * self) {
}


GType yrcd_yrcd_constants_get_type (void) {
	static volatile gsize yrcd_yrcd_constants_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_constants_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_constantsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_constants_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_constants), 0, (GInstanceInitFunc) yrcd_yrcd_constants_instance_init, NULL };
		GType yrcd_yrcd_constants_type_id;
		yrcd_yrcd_constants_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_constants", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_constants_type_id__volatile, yrcd_yrcd_constants_type_id);
	}
	return yrcd_yrcd_constants_type_id__volatile;
}



