/* numeric_wrapper.c generated by valac 0.24.0, the Vala compiler
 * generated from numeric_wrapper.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_YRCD_NUMERIC_WRAPPER (yrcd_yrcd_numeric_wrapper_get_type ())
#define YRCD_YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapper))
#define YRCD_YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapperClass))
#define YRCD_IS_YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER))
#define YRCD_IS_YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_NUMERIC_WRAPPER))
#define YRCD_YRCD_NUMERIC_WRAPPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapperClass))

typedef struct _yrcdyrcd_numeric_wrapper yrcdyrcd_numeric_wrapper;
typedef struct _yrcdyrcd_numeric_wrapperClass yrcdyrcd_numeric_wrapperClass;
typedef struct _yrcdyrcd_numeric_wrapperPrivate yrcdyrcd_numeric_wrapperPrivate;

#define YRCD_TYPE_YRCD_NUMERIC (yrcd_yrcd_numeric_get_type ())
#define YRCD_YRCD_NUMERIC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numeric))
#define YRCD_YRCD_NUMERIC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numericClass))
#define YRCD_IS_YRCD_NUMERIC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_NUMERIC))
#define YRCD_IS_YRCD_NUMERIC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_NUMERIC))
#define YRCD_YRCD_NUMERIC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numericClass))

typedef struct _yrcdyrcd_numeric yrcdyrcd_numeric;
typedef struct _yrcdyrcd_numericClass yrcdyrcd_numericClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _yrcdyrcd_numeric_wrapper {
	GObject parent_instance;
	yrcdyrcd_numeric_wrapperPrivate * priv;
	GeeHashMap* numerics;
};

struct _yrcdyrcd_numeric_wrapperClass {
	GObjectClass parent_class;
};


static gpointer yrcd_yrcd_numeric_wrapper_parent_class = NULL;

GType yrcd_yrcd_numeric_wrapper_get_type (void) G_GNUC_CONST;
GType yrcd_yrcd_numeric_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_YRCD_NUMERIC_WRAPPER_DUMMY_PROPERTY
};
yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_new (void);
yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_construct (GType object_type);
static void yrcd_yrcd_numeric_wrapper_register_numeric (yrcdyrcd_numeric_wrapper* self, const gchar* code, const gchar* numeric, const gchar* msg);
yrcdyrcd_numeric* yrcd_yrcd_numeric_new (const gchar* _numeric, const gchar* _code, const gchar* _msg);
yrcdyrcd_numeric* yrcd_yrcd_numeric_construct (GType object_type, const gchar* _numeric, const gchar* _code, const gchar* _msg);
static void yrcd_yrcd_numeric_wrapper_finalize (GObject* obj);


yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_construct (GType object_type) {
	yrcdyrcd_numeric_wrapper * self = NULL;
	self = (yrcdyrcd_numeric_wrapper*) g_object_new (object_type, NULL);
	yrcd_yrcd_numeric_wrapper_register_numeric (self, "RPL_WELCOME", "001", "Welcome to the Internet Relay Network %s!%s@%s");
	yrcd_yrcd_numeric_wrapper_register_numeric (self, "RPL_YOURHOST", "002", "Your host is %s, running version %s");
	yrcd_yrcd_numeric_wrapper_register_numeric (self, "RPL_CREATED", "003", "This server was created %s");
	yrcd_yrcd_numeric_wrapper_register_numeric (self, "RPL_MYINFO", "004", "%s %s %s %s");
	return self;
}


yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_new (void) {
	return yrcd_yrcd_numeric_wrapper_construct (YRCD_TYPE_YRCD_NUMERIC_WRAPPER);
}


static void yrcd_yrcd_numeric_wrapper_register_numeric (yrcdyrcd_numeric_wrapper* self, const gchar* code, const gchar* numeric, const gchar* msg) {
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	yrcdyrcd_numeric* _tmp5_ = NULL;
	yrcdyrcd_numeric* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (code != NULL);
	g_return_if_fail (numeric != NULL);
	g_return_if_fail (msg != NULL);
	_tmp0_ = self->numerics;
	_tmp1_ = code;
	_tmp2_ = numeric;
	_tmp3_ = code;
	_tmp4_ = msg;
	_tmp5_ = yrcd_yrcd_numeric_new (_tmp2_, _tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp0_, _tmp1_, _tmp6_);
	_g_object_unref0 (_tmp6_);
}


static void yrcd_yrcd_numeric_wrapper_class_init (yrcdyrcd_numeric_wrapperClass * klass) {
	yrcd_yrcd_numeric_wrapper_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_numeric_wrapper_finalize;
}


static void yrcd_yrcd_numeric_wrapper_instance_init (yrcdyrcd_numeric_wrapper * self) {
	GeeHashMap* _tmp0_ = NULL;
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, YRCD_TYPE_YRCD_NUMERIC, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->numerics = _tmp0_;
}


static void yrcd_yrcd_numeric_wrapper_finalize (GObject* obj) {
	yrcdyrcd_numeric_wrapper * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapper);
	_g_object_unref0 (self->numerics);
	G_OBJECT_CLASS (yrcd_yrcd_numeric_wrapper_parent_class)->finalize (obj);
}


GType yrcd_yrcd_numeric_wrapper_get_type (void) {
	static volatile gsize yrcd_yrcd_numeric_wrapper_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_numeric_wrapper_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_numeric_wrapperClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_numeric_wrapper_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_numeric_wrapper), 0, (GInstanceInitFunc) yrcd_yrcd_numeric_wrapper_instance_init, NULL };
		GType yrcd_yrcd_numeric_wrapper_type_id;
		yrcd_yrcd_numeric_wrapper_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_numeric_wrapper", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_numeric_wrapper_type_id__volatile, yrcd_yrcd_numeric_wrapper_type_id);
	}
	return yrcd_yrcd_numeric_wrapper_type_id__volatile;
}



