/* numerics.c generated by valac 0.24.0, the Vala compiler
 * generated from numerics.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_YRCD_NUMERIC_WRAPPER (yrcd_yrcd_numeric_wrapper_get_type ())
#define YRCD_YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapper))
#define YRCD_YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapperClass))
#define YRCD_IS_YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER))
#define YRCD_IS_YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_NUMERIC_WRAPPER))
#define YRCD_YRCD_NUMERIC_WRAPPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapperClass))

typedef struct _yrcdyrcd_numeric_wrapper yrcdyrcd_numeric_wrapper;
typedef struct _yrcdyrcd_numeric_wrapperClass yrcdyrcd_numeric_wrapperClass;
typedef struct _yrcdyrcd_numeric_wrapperPrivate yrcdyrcd_numeric_wrapperPrivate;

#define YRCD_YRCD_NUMERIC_WRAPPER_TYPE_NUM (yrcd_yrcd_numeric_wrapper_num_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _yrcdyrcd_numeric_wrapper {
	GObject parent_instance;
	yrcdyrcd_numeric_wrapperPrivate * priv;
	GeeHashMap* numerics;
};

struct _yrcdyrcd_numeric_wrapperClass {
	GObjectClass parent_class;
};

typedef enum  {
	YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_WELCOME = 001,
	YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_YOURHOST = 002,
	YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_CREATED = 003,
	YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_MYINFO = 004,
	YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NONICKNAMEGIVEN = 431,
	YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NICKNAMEINUSE = 432
} yrcdyrcd_numeric_wrapperNum;


static gpointer yrcd_yrcd_numeric_wrapper_parent_class = NULL;

GType yrcd_yrcd_numeric_wrapper_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_YRCD_NUMERIC_WRAPPER_DUMMY_PROPERTY
};
GType yrcd_yrcd_numeric_wrapper_num_get_type (void) G_GNUC_CONST;
yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_new (void);
yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_construct (GType object_type);
static void yrcd_yrcd_numeric_wrapper_finalize (GObject* obj);


GType yrcd_yrcd_numeric_wrapper_num_get_type (void) {
	static volatile gsize yrcd_yrcd_numeric_wrapper_num_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_numeric_wrapper_num_type_id__volatile)) {
		static const GEnumValue values[] = {{YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_WELCOME, "YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_WELCOME", "rpl-welcome"}, {YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_YOURHOST, "YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_YOURHOST", "rpl-yourhost"}, {YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_CREATED, "YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_CREATED", "rpl-created"}, {YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_MYINFO, "YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_MYINFO", "rpl-myinfo"}, {YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NONICKNAMEGIVEN, "YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NONICKNAMEGIVEN", "err-nonicknamegiven"}, {YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NICKNAMEINUSE, "YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NICKNAMEINUSE", "err-nicknameinuse"}, {0, NULL, NULL}};
		GType yrcd_yrcd_numeric_wrapper_num_type_id;
		yrcd_yrcd_numeric_wrapper_num_type_id = g_enum_register_static ("yrcdyrcd_numeric_wrapperNum", values);
		g_once_init_leave (&yrcd_yrcd_numeric_wrapper_num_type_id__volatile, yrcd_yrcd_numeric_wrapper_num_type_id);
	}
	return yrcd_yrcd_numeric_wrapper_num_type_id__volatile;
}


yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_construct (GType object_type) {
	yrcdyrcd_numeric_wrapper * self = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	self = (yrcdyrcd_numeric_wrapper*) g_object_new (object_type, NULL);
	_tmp0_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp0_, (gpointer) ((gintptr) ((gint) YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_WELCOME)), "Welcome to the Internet Relay Network %s!%s@%s");
	_tmp1_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp1_, (gpointer) ((gintptr) ((gint) YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_YOURHOST)), "Your host is %s, running %s version %s");
	_tmp2_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp2_, (gpointer) ((gintptr) ((gint) YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_CREATED)), "This server was created %s");
	_tmp3_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, (gpointer) ((gintptr) ((gint) YRCD_YRCD_NUMERIC_WRAPPER_NUM_RPL_MYINFO)), "%s %s %s %s");
	_tmp4_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, (gpointer) ((gintptr) ((gint) YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NONICKNAMEGIVEN)), "No nickname given");
	_tmp5_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, (gpointer) ((gintptr) ((gint) YRCD_YRCD_NUMERIC_WRAPPER_NUM_ERR_NICKNAMEINUSE)), "%s :Nickname is already in use");
	return self;
}


yrcdyrcd_numeric_wrapper* yrcd_yrcd_numeric_wrapper_new (void) {
	return yrcd_yrcd_numeric_wrapper_construct (YRCD_TYPE_YRCD_NUMERIC_WRAPPER);
}


static void yrcd_yrcd_numeric_wrapper_class_init (yrcdyrcd_numeric_wrapperClass * klass) {
	yrcd_yrcd_numeric_wrapper_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_numeric_wrapper_finalize;
}


static void yrcd_yrcd_numeric_wrapper_instance_init (yrcdyrcd_numeric_wrapper * self) {
	GeeHashMap* _tmp0_ = NULL;
	_tmp0_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	self->numerics = _tmp0_;
}


static void yrcd_yrcd_numeric_wrapper_finalize (GObject* obj) {
	yrcdyrcd_numeric_wrapper * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapper);
	_g_object_unref0 (self->numerics);
	G_OBJECT_CLASS (yrcd_yrcd_numeric_wrapper_parent_class)->finalize (obj);
}


GType yrcd_yrcd_numeric_wrapper_get_type (void) {
	static volatile gsize yrcd_yrcd_numeric_wrapper_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_numeric_wrapper_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_numeric_wrapperClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_numeric_wrapper_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_numeric_wrapper), 0, (GInstanceInitFunc) yrcd_yrcd_numeric_wrapper_instance_init, NULL };
		GType yrcd_yrcd_numeric_wrapper_type_id;
		yrcd_yrcd_numeric_wrapper_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_numeric_wrapper", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_numeric_wrapper_type_id__volatile, yrcd_yrcd_numeric_wrapper_type_id);
	}
	return yrcd_yrcd_numeric_wrapper_type_id__volatile;
}



