/* numeric.c generated by valac 0.24.0, the Vala compiler
 * generated from numeric.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_YRCD_NUMERIC (yrcd_yrcd_numeric_get_type ())
#define YRCD_YRCD_NUMERIC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numeric))
#define YRCD_YRCD_NUMERIC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numericClass))
#define YRCD_IS_YRCD_NUMERIC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_NUMERIC))
#define YRCD_IS_YRCD_NUMERIC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_NUMERIC))
#define YRCD_YRCD_NUMERIC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numericClass))

typedef struct _yrcdyrcd_numeric yrcdyrcd_numeric;
typedef struct _yrcdyrcd_numericClass yrcdyrcd_numericClass;
typedef struct _yrcdyrcd_numericPrivate yrcdyrcd_numericPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _yrcdyrcd_numeric {
	GObject parent_instance;
	yrcdyrcd_numericPrivate * priv;
};

struct _yrcdyrcd_numericClass {
	GObjectClass parent_class;
};

struct _yrcdyrcd_numericPrivate {
	gint _numeric;
	gchar* _code;
	gchar* _msg;
};


static gpointer yrcd_yrcd_numeric_parent_class = NULL;

GType yrcd_yrcd_numeric_get_type (void) G_GNUC_CONST;
#define YRCD_YRCD_NUMERIC_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numericPrivate))
enum  {
	YRCD_YRCD_NUMERIC_DUMMY_PROPERTY,
	YRCD_YRCD_NUMERIC_NUMERIC,
	YRCD_YRCD_NUMERIC_CODE,
	YRCD_YRCD_NUMERIC_MSG
};
yrcdyrcd_numeric* yrcd_yrcd_numeric_new (gint _numeric, const gchar* _code, const gchar* _msg);
yrcdyrcd_numeric* yrcd_yrcd_numeric_construct (GType object_type, gint _numeric, const gchar* _code, const gchar* _msg);
void yrcd_yrcd_numeric_set_numeric (yrcdyrcd_numeric* self, gint value);
void yrcd_yrcd_numeric_set_code (yrcdyrcd_numeric* self, const gchar* value);
void yrcd_yrcd_numeric_set_msg (yrcdyrcd_numeric* self, const gchar* value);
gint yrcd_yrcd_numeric_get_numeric (yrcdyrcd_numeric* self);
const gchar* yrcd_yrcd_numeric_get_code (yrcdyrcd_numeric* self);
const gchar* yrcd_yrcd_numeric_get_msg (yrcdyrcd_numeric* self);
static void yrcd_yrcd_numeric_finalize (GObject* obj);
static void _vala_yrcd_yrcd_numeric_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_yrcd_yrcd_numeric_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


yrcdyrcd_numeric* yrcd_yrcd_numeric_construct (GType object_type, gint _numeric, const gchar* _code, const gchar* _msg) {
	yrcdyrcd_numeric * self = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	g_return_val_if_fail (_code != NULL, NULL);
	g_return_val_if_fail (_msg != NULL, NULL);
	self = (yrcdyrcd_numeric*) g_object_new (object_type, NULL);
	_tmp0_ = _numeric;
	yrcd_yrcd_numeric_set_numeric (self, _tmp0_);
	_tmp1_ = _code;
	yrcd_yrcd_numeric_set_code (self, _tmp1_);
	_tmp2_ = _msg;
	yrcd_yrcd_numeric_set_msg (self, _tmp2_);
	return self;
}


yrcdyrcd_numeric* yrcd_yrcd_numeric_new (gint _numeric, const gchar* _code, const gchar* _msg) {
	return yrcd_yrcd_numeric_construct (YRCD_TYPE_YRCD_NUMERIC, _numeric, _code, _msg);
}


gint yrcd_yrcd_numeric_get_numeric (yrcdyrcd_numeric* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_numeric;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_numeric_set_numeric (yrcdyrcd_numeric* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_numeric = _tmp0_;
	g_object_notify ((GObject *) self, "numeric");
}


const gchar* yrcd_yrcd_numeric_get_code (yrcdyrcd_numeric* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_code;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_numeric_set_code (yrcdyrcd_numeric* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_code);
	self->priv->_code = _tmp1_;
	g_object_notify ((GObject *) self, "code");
}


const gchar* yrcd_yrcd_numeric_get_msg (yrcdyrcd_numeric* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_msg;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_numeric_set_msg (yrcdyrcd_numeric* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_msg);
	self->priv->_msg = _tmp1_;
	g_object_notify ((GObject *) self, "msg");
}


static void yrcd_yrcd_numeric_class_init (yrcdyrcd_numericClass * klass) {
	yrcd_yrcd_numeric_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (yrcdyrcd_numericPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_yrcd_yrcd_numeric_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_yrcd_yrcd_numeric_set_property;
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_numeric_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_NUMERIC_NUMERIC, g_param_spec_int ("numeric", "numeric", "numeric", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_NUMERIC_CODE, g_param_spec_string ("code", "code", "code", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_NUMERIC_MSG, g_param_spec_string ("msg", "msg", "msg", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void yrcd_yrcd_numeric_instance_init (yrcdyrcd_numeric * self) {
	self->priv = YRCD_YRCD_NUMERIC_GET_PRIVATE (self);
}


static void yrcd_yrcd_numeric_finalize (GObject* obj) {
	yrcdyrcd_numeric * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numeric);
	_g_free0 (self->priv->_code);
	_g_free0 (self->priv->_msg);
	G_OBJECT_CLASS (yrcd_yrcd_numeric_parent_class)->finalize (obj);
}


GType yrcd_yrcd_numeric_get_type (void) {
	static volatile gsize yrcd_yrcd_numeric_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_numeric_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_numericClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_numeric_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_numeric), 0, (GInstanceInitFunc) yrcd_yrcd_numeric_instance_init, NULL };
		GType yrcd_yrcd_numeric_type_id;
		yrcd_yrcd_numeric_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_numeric", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_numeric_type_id__volatile, yrcd_yrcd_numeric_type_id);
	}
	return yrcd_yrcd_numeric_type_id__volatile;
}


static void _vala_yrcd_yrcd_numeric_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	yrcdyrcd_numeric * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numeric);
	switch (property_id) {
		case YRCD_YRCD_NUMERIC_NUMERIC:
		g_value_set_int (value, yrcd_yrcd_numeric_get_numeric (self));
		break;
		case YRCD_YRCD_NUMERIC_CODE:
		g_value_set_string (value, yrcd_yrcd_numeric_get_code (self));
		break;
		case YRCD_YRCD_NUMERIC_MSG:
		g_value_set_string (value, yrcd_yrcd_numeric_get_msg (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_yrcd_yrcd_numeric_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	yrcdyrcd_numeric * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_NUMERIC, yrcdyrcd_numeric);
	switch (property_id) {
		case YRCD_YRCD_NUMERIC_NUMERIC:
		yrcd_yrcd_numeric_set_numeric (self, g_value_get_int (value));
		break;
		case YRCD_YRCD_NUMERIC_CODE:
		yrcd_yrcd_numeric_set_code (self, g_value_get_string (value));
		break;
		case YRCD_YRCD_NUMERIC_MSG:
		yrcd_yrcd_numeric_set_msg (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



