/* numerics.c generated by valac 0.25.1, the Vala compiler
 * generated from numerics.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_NUMERIC_WRAPPER (yrcd_numeric_wrapper_get_type ())
#define YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapper))
#define YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapperClass))
#define YRCD_IS_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_NUMERIC_WRAPPER))
#define YRCD_IS_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_NUMERIC_WRAPPER))
#define YRCD_NUMERIC_WRAPPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapperClass))

typedef struct _yrcdNumericWrapper yrcdNumericWrapper;
typedef struct _yrcdNumericWrapperClass yrcdNumericWrapperClass;
typedef struct _yrcdNumericWrapperPrivate yrcdNumericWrapperPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _yrcdNumericWrapper {
	GObject parent_instance;
	yrcdNumericWrapperPrivate * priv;
	GeeHashMap* numerics;
};

struct _yrcdNumericWrapperClass {
	GObjectClass parent_class;
};


static gpointer yrcd_numeric_wrapper_parent_class = NULL;

GType yrcd_numeric_wrapper_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_NUMERIC_WRAPPER_DUMMY_PROPERTY
};
yrcdNumericWrapper* yrcd_numeric_wrapper_new (void);
yrcdNumericWrapper* yrcd_numeric_wrapper_construct (GType object_type);
#define YRCD_RPL_WELCOME 001
#define YRCD_RPL_YOURHOST 002
#define YRCD_RPL_CREATED 003
#define YRCD_RPL_MYINFO 004
#define YRCD_RPL_ENDOFWHO 315
#define YRCD_RPL_TOPIC 332
#define YRCD_RPL_TOPICWHOTIME 333
#define YRCD_RPL_WHOREPLY 352
#define YRCD_RPL_NAMEPLY 353
#define YRCD_RPL_ENDOFNAMES 366
#define YRCD_RPL_MOTD 372
#define YRCD_RPL_MOTDSTART 375
#define YRCD_RPL_ENDOFMOTD 376
#define YRCD_ERR_NOSUCHCHANNEL 403
#define YRCD_ERR_UNKNOWNCOMMAND 421
#define YRCD_ERR_NONICKNAMEGIVEN 431
#define YRCD_ERR_NICKNAMEINUSE 433
#define YRCD_ERR_ERRONEOUSNICKNAME 432
#define YRCD_ERR_NOTREGISTERED 451
#define YRCD_ERR_NEEDMOREPARAMS 461
#define YRCD_ERR_ALREADYREGISTRED 462
static void yrcd_numeric_wrapper_finalize (GObject* obj);


yrcdNumericWrapper* yrcd_numeric_wrapper_construct (GType object_type) {
	yrcdNumericWrapper * self = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	GeeHashMap* _tmp6_ = NULL;
	GeeHashMap* _tmp7_ = NULL;
	GeeHashMap* _tmp8_ = NULL;
	GeeHashMap* _tmp9_ = NULL;
	GeeHashMap* _tmp10_ = NULL;
	GeeHashMap* _tmp11_ = NULL;
	GeeHashMap* _tmp12_ = NULL;
	GeeHashMap* _tmp13_ = NULL;
	GeeHashMap* _tmp14_ = NULL;
	GeeHashMap* _tmp15_ = NULL;
	GeeHashMap* _tmp16_ = NULL;
	GeeHashMap* _tmp17_ = NULL;
	GeeHashMap* _tmp18_ = NULL;
	GeeHashMap* _tmp19_ = NULL;
	GeeHashMap* _tmp20_ = NULL;
	self = (yrcdNumericWrapper*) g_object_new (object_type, NULL);
	_tmp0_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp0_, (gpointer) ((gintptr) YRCD_RPL_WELCOME), "Welcome to the Internet Relay Network %s!%s@%s");
	_tmp1_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp1_, (gpointer) ((gintptr) YRCD_RPL_YOURHOST), "Your host is %s, running %s version %s");
	_tmp2_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp2_, (gpointer) ((gintptr) YRCD_RPL_CREATED), "This server was created %s");
	_tmp3_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, (gpointer) ((gintptr) YRCD_RPL_MYINFO), "%s %s %s %s");
	_tmp4_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, (gpointer) ((gintptr) YRCD_RPL_ENDOFWHO), "%s :End of WHO list");
	_tmp5_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, (gpointer) ((gintptr) YRCD_RPL_TOPIC), "%s :%s");
	_tmp6_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp6_, (gpointer) ((gintptr) YRCD_RPL_TOPICWHOTIME), "%s %s %s");
	_tmp7_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp7_, (gpointer) ((gintptr) YRCD_RPL_WHOREPLY), "%s %s %s %s %s %s %s %s");
	_tmp8_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp8_, (gpointer) ((gintptr) YRCD_RPL_NAMEPLY), "= %s :%s");
	_tmp9_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp9_, (gpointer) ((gintptr) YRCD_RPL_ENDOFNAMES), "%s :End of /NAMES list.");
	_tmp10_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp10_, (gpointer) ((gintptr) YRCD_RPL_MOTD), ":- %s");
	_tmp11_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp11_, (gpointer) ((gintptr) YRCD_RPL_MOTDSTART), ":- %s Message of the day -");
	_tmp12_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp12_, (gpointer) ((gintptr) YRCD_RPL_ENDOFMOTD), ":End of /MOTD command.");
	_tmp13_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp13_, (gpointer) ((gintptr) YRCD_ERR_NOSUCHCHANNEL), "%s :No such channel");
	_tmp14_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp14_, (gpointer) ((gintptr) YRCD_ERR_UNKNOWNCOMMAND), "%s :Unkown command");
	_tmp15_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp15_, (gpointer) ((gintptr) YRCD_ERR_NONICKNAMEGIVEN), "No nickname given");
	_tmp16_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp16_, (gpointer) ((gintptr) YRCD_ERR_NICKNAMEINUSE), "%s :Nickname is already in use");
	_tmp17_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp17_, (gpointer) ((gintptr) YRCD_ERR_ERRONEOUSNICKNAME), "%s :Erroneous nickname");
	_tmp18_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp18_, (gpointer) ((gintptr) YRCD_ERR_NOTREGISTERED), ":You have not registered");
	_tmp19_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp19_, (gpointer) ((gintptr) YRCD_ERR_NEEDMOREPARAMS), "%s :Not enough parameters");
	_tmp20_ = self->numerics;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp20_, (gpointer) ((gintptr) YRCD_ERR_ALREADYREGISTRED), "You may not reregister");
	return self;
}


yrcdNumericWrapper* yrcd_numeric_wrapper_new (void) {
	return yrcd_numeric_wrapper_construct (YRCD_TYPE_NUMERIC_WRAPPER);
}


static void yrcd_numeric_wrapper_class_init (yrcdNumericWrapperClass * klass) {
	yrcd_numeric_wrapper_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = yrcd_numeric_wrapper_finalize;
}


static void yrcd_numeric_wrapper_instance_init (yrcdNumericWrapper * self) {
	GeeHashMap* _tmp0_ = NULL;
	_tmp0_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	self->numerics = _tmp0_;
}


static void yrcd_numeric_wrapper_finalize (GObject* obj) {
	yrcdNumericWrapper * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapper);
	_g_object_unref0 (self->numerics);
	G_OBJECT_CLASS (yrcd_numeric_wrapper_parent_class)->finalize (obj);
}


GType yrcd_numeric_wrapper_get_type (void) {
	static volatile gsize yrcd_numeric_wrapper_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_numeric_wrapper_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdNumericWrapperClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_numeric_wrapper_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdNumericWrapper), 0, (GInstanceInitFunc) yrcd_numeric_wrapper_instance_init, NULL };
		GType yrcd_numeric_wrapper_type_id;
		yrcd_numeric_wrapper_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdNumericWrapper", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_numeric_wrapper_type_id__volatile, yrcd_numeric_wrapper_type_id);
	}
	return yrcd_numeric_wrapper_type_id__volatile;
}



