/* router.c generated by valac 0.25.1, the Vala compiler
 * generated from router.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gee.h>


#define YRCD_TYPE_BASE_OBJECT (yrcd_base_object_get_type ())
#define YRCD_BASE_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_BASE_OBJECT, yrcdBaseObject))
#define YRCD_BASE_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_BASE_OBJECT, yrcdBaseObjectClass))
#define YRCD_IS_BASE_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_BASE_OBJECT))
#define YRCD_IS_BASE_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_BASE_OBJECT))
#define YRCD_BASE_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_BASE_OBJECT, yrcdBaseObjectClass))

typedef struct _yrcdBaseObject yrcdBaseObject;
typedef struct _yrcdBaseObjectClass yrcdBaseObjectClass;
typedef struct _yrcdBaseObjectPrivate yrcdBaseObjectPrivate;

#define YRCD_TYPE_ROUTER (yrcd_router_get_type ())
#define YRCD_ROUTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_ROUTER, yrcdRouter))
#define YRCD_ROUTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_ROUTER, yrcdRouterClass))
#define YRCD_IS_ROUTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_ROUTER))
#define YRCD_IS_ROUTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_ROUTER))
#define YRCD_ROUTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_ROUTER, yrcdRouterClass))

typedef struct _yrcdRouter yrcdRouter;
typedef struct _yrcdRouterClass yrcdRouterClass;
typedef struct _yrcdRouterPrivate yrcdRouterPrivate;

#define YRCD_TYPE_SERVER (yrcd_server_get_type ())
#define YRCD_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_SERVER, yrcdServer))
#define YRCD_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_SERVER, yrcdServerClass))
#define YRCD_IS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_SERVER))
#define YRCD_IS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_SERVER))
#define YRCD_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_SERVER, yrcdServerClass))

typedef struct _yrcdServer yrcdServer;
typedef struct _yrcdServerClass yrcdServerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define YRCD_TYPE_USER (yrcd_user_get_type ())
#define YRCD_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_USER, yrcdUser))
#define YRCD_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_USER, yrcdUserClass))
#define YRCD_IS_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_USER))
#define YRCD_IS_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_USER))
#define YRCD_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_USER, yrcdUserClass))

typedef struct _yrcdUser yrcdUser;
typedef struct _yrcdUserClass yrcdUserClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define YRCD_TYPE_CHANNEL (yrcd_channel_get_type ())
#define YRCD_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_CHANNEL, yrcdChannel))
#define YRCD_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_CHANNEL, yrcdChannelClass))
#define YRCD_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_CHANNEL))
#define YRCD_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_CHANNEL))
#define YRCD_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_CHANNEL, yrcdChannelClass))

typedef struct _yrcdChannel yrcdChannel;
typedef struct _yrcdChannelClass yrcdChannelClass;
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
typedef struct _yrcdChannelPrivate yrcdChannelPrivate;
typedef struct _yrcdServerPrivate yrcdServerPrivate;

#define YRCD_TYPE_NUMERIC_WRAPPER (yrcd_numeric_wrapper_get_type ())
#define YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapper))
#define YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapperClass))
#define YRCD_IS_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_NUMERIC_WRAPPER))
#define YRCD_IS_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_NUMERIC_WRAPPER))
#define YRCD_NUMERIC_WRAPPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_NUMERIC_WRAPPER, yrcdNumericWrapperClass))

typedef struct _yrcdNumericWrapper yrcdNumericWrapper;
typedef struct _yrcdNumericWrapperClass yrcdNumericWrapperClass;

#define YRCD_TYPE_CONFIG (yrcd_config_get_type ())
#define YRCD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_CONFIG, yrcdConfig))
#define YRCD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_CONFIG, yrcdConfigClass))
#define YRCD_IS_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_CONFIG))
#define YRCD_IS_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_CONFIG))
#define YRCD_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_CONFIG, yrcdConfigClass))

typedef struct _yrcdConfig yrcdConfig;
typedef struct _yrcdConfigClass yrcdConfigClass;
typedef struct _yrcdConfigPrivate yrcdConfigPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _YrcdRouterProcessUserData YrcdRouterProcessUserData;

struct _yrcdBaseObject {
	GObject parent_instance;
	yrcdBaseObjectPrivate * priv;
};

struct _yrcdBaseObjectClass {
	GObjectClass parent_class;
};

struct _yrcdRouter {
	yrcdBaseObject parent_instance;
	yrcdRouterPrivate * priv;
	yrcdServer* server;
};

struct _yrcdRouterClass {
	yrcdBaseObjectClass parent_class;
};

struct _yrcdChannel {
	yrcdBaseObject parent_instance;
	yrcdChannelPrivate * priv;
	gchar** modes;
	gint modes_length1;
	gint _modes_size_;
	gchar* topic;
	gint64 epoch;
	gint64 topictime;
	gchar* topic_host;
	yrcdServer* server;
	GList* users;
	guint timer;
};

struct _yrcdChannelClass {
	yrcdBaseObjectClass parent_class;
};

struct _yrcdServer {
	yrcdBaseObject parent_instance;
	yrcdServerPrivate * priv;
	GeeHashMap* userlist;
	GeeHashMap* channellist;
	gint64 epoch;
	gint max_users;
	yrcdNumericWrapper* numeric_wrapper;
	yrcdConfig* config;
};

struct _yrcdServerClass {
	yrcdBaseObjectClass parent_class;
};

struct _yrcdConfig {
	yrcdBaseObject parent_instance;
	yrcdConfigPrivate * priv;
	GList* listen_ports;
	gchar** listen_ips;
	gint listen_ips_length1;
	GList* motd;
	gint ping_invertal;
	gint max_users;
	gint max_nick_length;
	gboolean config_error;
	gboolean cloaking;
	gchar* salt;
};

struct _yrcdConfigClass {
	yrcdBaseObjectClass parent_class;
};

struct _YrcdRouterProcessUserData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	yrcdRouter* self;
	GSocketConnection* conn;
	gboolean _tmp0_;
	yrcdServer* _tmp1_;
	GeeHashMap* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	yrcdServer* _tmp5_;
	yrcdConfig* _tmp6_;
	gint _tmp7_;
	yrcdServer* _tmp8_;
	yrcdConfig* _tmp9_;
	gint _tmp10_;
	GSocketConnection* _tmp11_;
	GSocket* _tmp12_;
	GError* e;
	yrcdServer* _tmp13_;
	GError* _tmp14_;
	const gchar* _tmp15_;
	yrcdServer* _tmp16_;
	yrcdServer* _tmp17_;
	yrcdConfig* _tmp18_;
	gint _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	yrcdUser* user;
	GSocketConnection* _tmp22_;
	yrcdServer* _tmp23_;
	yrcdUser* _tmp24_;
	yrcdServer* _tmp25_;
	GeeHashMap* _tmp26_;
	yrcdUser* _tmp27_;
	gint _tmp28_;
	gint _tmp29_;
	yrcdUser* _tmp30_;
	yrcdServer* _tmp31_;
	GeeHashMap* _tmp32_;
	gint _tmp33_;
	gint _tmp34_;
	yrcdServer* _tmp35_;
	gint _tmp36_;
	yrcdServer* _tmp37_;
	yrcdServer* _tmp38_;
	GeeHashMap* _tmp39_;
	gint _tmp40_;
	gint _tmp41_;
	yrcdServer* _tmp42_;
	yrcdServer* _tmp43_;
	gint _tmp44_;
	gchar* _tmp45_;
	gchar* _tmp46_;
	GSocket* socket;
	yrcdUser* _tmp47_;
	GSocketConnection* _tmp48_;
	GSocketConnection* _tmp49_;
	GSocket* _tmp50_;
	GSocket* _tmp51_;
	GSocket* _tmp52_;
	gboolean _tmp53_;
	gchar* msg;
	yrcdUser* _tmp54_;
	GDataInputStream* _tmp55_;
	GDataInputStream* _tmp56_;
	gchar* _tmp57_;
	yrcdUser* _tmp58_;
	const gchar* _tmp59_;
	GError* _vala1_e;
	yrcdServer* _tmp60_;
	GError* _tmp61_;
	const gchar* _tmp62_;
	gchar* _tmp63_;
	gchar* _tmp64_;
	yrcdUser* _tmp65_;
	GError * _inner_error_;
};


static gpointer yrcd_router_parent_class = NULL;

GType yrcd_base_object_get_type (void) G_GNUC_CONST;
GType yrcd_router_get_type (void) G_GNUC_CONST;
GType yrcd_server_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_ROUTER_DUMMY_PROPERTY
};
yrcdRouter* yrcd_router_new (yrcdServer* k);
yrcdRouter* yrcd_router_construct (GType object_type, yrcdServer* k);
yrcdBaseObject* yrcd_base_object_construct (GType object_type);
GType yrcd_user_get_type (void) G_GNUC_CONST;
void yrcd_router_route (yrcdRouter* self, yrcdUser* user, const gchar* msg);
yrcdServer* yrcd_user_get_server (yrcdUser* self);
void yrcd_server_log (yrcdServer* self, const gchar* msg);
gint yrcd_user_get_id (yrcdUser* self);
void yrcd_user_quit (yrcdUser* self, const gchar* msg);
void yrcd_user_update_timestamp (yrcdUser* self);
void yrcd_router_quit_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
void yrcd_user_change_nick (yrcdUser* self, gchar** args, int args_length1);
void yrcd_user_user_reg (yrcdUser* self, gchar** args, int args_length1);
void yrcd_router_privmsg_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
void yrcd_router_join_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
void yrcd_user_fire_motd (yrcdUser* self);
void yrcd_router_ping_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
void yrcd_router_who_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
void yrcd_router_part_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
void yrcd_router_unknown_command_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1);
gboolean yrcd_user_get_registered (yrcdUser* self);
void yrcd_user_fire_numeric (yrcdUser* self, gint numeric, ...);
#define YRCD_ERR_NOTREGISTERED 451
gchar* yrcd_router_assemble (yrcdRouter* self, gint position, gchar** args, int args_length1);
GType yrcd_channel_get_type (void) G_GNUC_CONST;
yrcdChannel* yrcd_server_get_channel_by_name (yrcdServer* self, const gchar* nametocheck);
void yrcd_user_part (yrcdUser* self, yrcdChannel* chan, const gchar* msg);
void yrcd_channel_who_response (yrcdChannel* self, yrcdUser* user);
void yrcd_user_send_line (yrcdUser* self, const gchar* msg, gint p);
#define YRCD_ERR_UNKNOWNCOMMAND 421
#define YRCD_ERR_NEEDMOREPARAMS 461
gboolean yrcd_router_valid_chan_name (yrcdRouter* self, const gchar* chan);
#define YRCD_ERR_NOSUCHCHANNEL 403
void yrcd_user_join (yrcdUser* self, yrcdChannel* chan);
void yrcd_channel_privmsg (yrcdChannel* self, yrcdUser* user, const gchar* msg);
yrcdUser* yrcd_server_get_user_by_nick (yrcdServer* self, const gchar* nicktocheck);
static void yrcd_router_process_user_data_free (gpointer _data);
void yrcd_router_process_user (yrcdRouter* self, GSocketConnection* conn, GAsyncReadyCallback _callback_, gpointer _user_data_);
void yrcd_router_process_user_finish (yrcdRouter* self, GAsyncResult* _res_);
static gboolean yrcd_router_process_user_co (YrcdRouterProcessUserData* _data_);
GType yrcd_numeric_wrapper_get_type (void) G_GNUC_CONST;
GType yrcd_config_get_type (void) G_GNUC_CONST;
yrcdUser* yrcd_user_new (GSocketConnection* conn, yrcdServer* _server);
yrcdUser* yrcd_user_construct (GType object_type, GSocketConnection* conn, yrcdServer* _server);
GSocketConnection* yrcd_user_get_sock (yrcdUser* self);
GDataInputStream* yrcd_user_get_dis (yrcdUser* self);
static void yrcd_router_process_user_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void yrcd_router_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

extern const gchar* YRCD_CONSTANTS_chan_prefixes[2];
extern const gchar* YRCD_CONSTANTS_chan_forbidden[5];

static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


yrcdRouter* yrcd_router_construct (GType object_type, yrcdServer* k) {
	yrcdRouter * self = NULL;
	yrcdServer* _tmp0_ = NULL;
	yrcdServer* _tmp1_ = NULL;
	g_return_val_if_fail (k != NULL, NULL);
	self = (yrcdRouter*) yrcd_base_object_construct (object_type);
	_tmp0_ = k;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->server);
	self->server = _tmp1_;
	return self;
}


yrcdRouter* yrcd_router_new (yrcdServer* k) {
	return yrcd_router_construct (YRCD_TYPE_ROUTER, k);
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


void yrcd_router_route (yrcdRouter* self, yrcdUser* user, const gchar* msg) {
	const gchar* _tmp0_ = NULL;
	gchar* stripped = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar** args = NULL;
	const gchar* _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gchar** _tmp14_ = NULL;
	gint args_length1 = 0;
	gint _args_size_ = 0;
	gchar** _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	const gchar* _tmp16_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = msg;
	if (_tmp0_ == NULL) {
		yrcdUser* _tmp1_ = NULL;
		yrcdServer* _tmp2_ = NULL;
		yrcdServer* _tmp3_ = NULL;
		yrcdUser* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		yrcdUser* _tmp9_ = NULL;
		_tmp1_ = user;
		_tmp2_ = yrcd_user_get_server (_tmp1_);
		_tmp3_ = _tmp2_;
		_tmp4_ = user;
		_tmp5_ = yrcd_user_get_id (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_strdup_printf ("Received null message, disconnecting user %d", _tmp6_);
		_tmp8_ = _tmp7_;
		yrcd_server_log (_tmp3_, _tmp8_);
		_g_free0 (_tmp8_);
		_tmp9_ = user;
		yrcd_user_quit (_tmp9_, NULL);
		return;
	}
	_tmp10_ = msg;
	_tmp11_ = string_strip (_tmp10_);
	stripped = _tmp11_;
	_tmp12_ = stripped;
	_tmp14_ = _tmp13_ = g_strsplit (_tmp12_, " ", 0);
	args = _tmp14_;
	args_length1 = _vala_array_length (_tmp13_);
	_args_size_ = args_length1;
	_tmp15_ = args;
	_tmp15__length1 = args_length1;
	_tmp16_ = _tmp15_[0];
	if (_tmp16_ != NULL) {
		yrcdUser* _tmp17_ = NULL;
		yrcdServer* _tmp18_ = NULL;
		yrcdServer* _tmp19_ = NULL;
		yrcdUser* _tmp20_ = NULL;
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		const gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
		yrcdUser* _tmp26_ = NULL;
		gchar** _tmp27_ = NULL;
		gint _tmp27__length1 = 0;
		const gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		GQuark _tmp32_ = 0U;
		static GQuark _tmp31_label0 = 0;
		static GQuark _tmp31_label1 = 0;
		static GQuark _tmp31_label2 = 0;
		static GQuark _tmp31_label3 = 0;
		static GQuark _tmp31_label4 = 0;
		static GQuark _tmp31_label5 = 0;
		static GQuark _tmp31_label6 = 0;
		static GQuark _tmp31_label7 = 0;
		static GQuark _tmp31_label8 = 0;
		static GQuark _tmp31_label9 = 0;
		_tmp17_ = user;
		_tmp18_ = yrcd_user_get_server (_tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = user;
		_tmp21_ = yrcd_user_get_id (_tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = stripped;
		_tmp24_ = g_strdup_printf ("USER %d: received line %s", _tmp22_, _tmp23_);
		_tmp25_ = _tmp24_;
		yrcd_server_log (_tmp19_, _tmp25_);
		_g_free0 (_tmp25_);
		_tmp26_ = user;
		yrcd_user_update_timestamp (_tmp26_);
		_tmp27_ = args;
		_tmp27__length1 = args_length1;
		_tmp28_ = _tmp27_[0];
		_tmp29_ = g_utf8_strdown (_tmp28_, (gssize) (-1));
		_tmp30_ = _tmp29_;
		_tmp32_ = (NULL == _tmp30_) ? 0 : g_quark_from_string (_tmp30_);
		g_free (_tmp30_);
		if (_tmp32_ == ((0 != _tmp31_label0) ? _tmp31_label0 : (_tmp31_label0 = g_quark_from_static_string ("quit")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp33_ = NULL;
					gchar** _tmp34_ = NULL;
					gint _tmp34__length1 = 0;
					_tmp33_ = user;
					_tmp34_ = args;
					_tmp34__length1 = args_length1;
					yrcd_router_quit_handler (self, _tmp33_, _tmp34_, _tmp34__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label1) ? _tmp31_label1 : (_tmp31_label1 = g_quark_from_static_string ("nick")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp35_ = NULL;
					gchar** _tmp36_ = NULL;
					gint _tmp36__length1 = 0;
					_tmp35_ = user;
					_tmp36_ = args;
					_tmp36__length1 = args_length1;
					yrcd_user_change_nick (_tmp35_, _tmp36_, _tmp36__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label2) ? _tmp31_label2 : (_tmp31_label2 = g_quark_from_static_string ("user")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp37_ = NULL;
					gchar** _tmp38_ = NULL;
					gint _tmp38__length1 = 0;
					_tmp37_ = user;
					_tmp38_ = args;
					_tmp38__length1 = args_length1;
					yrcd_user_user_reg (_tmp37_, _tmp38_, _tmp38__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label3) ? _tmp31_label3 : (_tmp31_label3 = g_quark_from_static_string ("privmsg")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp39_ = NULL;
					gchar** _tmp40_ = NULL;
					gint _tmp40__length1 = 0;
					_tmp39_ = user;
					_tmp40_ = args;
					_tmp40__length1 = args_length1;
					yrcd_router_privmsg_handler (self, _tmp39_, _tmp40_, _tmp40__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label4) ? _tmp31_label4 : (_tmp31_label4 = g_quark_from_static_string ("join")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp41_ = NULL;
					gchar** _tmp42_ = NULL;
					gint _tmp42__length1 = 0;
					_tmp41_ = user;
					_tmp42_ = args;
					_tmp42__length1 = args_length1;
					yrcd_router_join_handler (self, _tmp41_, _tmp42_, _tmp42__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label5) ? _tmp31_label5 : (_tmp31_label5 = g_quark_from_static_string ("pong")))) {
			switch (0) {
				default:
				{
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label6) ? _tmp31_label6 : (_tmp31_label6 = g_quark_from_static_string ("motd")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp43_ = NULL;
					_tmp43_ = user;
					yrcd_user_fire_motd (_tmp43_);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label7) ? _tmp31_label7 : (_tmp31_label7 = g_quark_from_static_string ("ping")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp44_ = NULL;
					gchar** _tmp45_ = NULL;
					gint _tmp45__length1 = 0;
					_tmp44_ = user;
					_tmp45_ = args;
					_tmp45__length1 = args_length1;
					yrcd_router_ping_handler (self, _tmp44_, _tmp45_, _tmp45__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label8) ? _tmp31_label8 : (_tmp31_label8 = g_quark_from_static_string ("who")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp46_ = NULL;
					gchar** _tmp47_ = NULL;
					gint _tmp47__length1 = 0;
					_tmp46_ = user;
					_tmp47_ = args;
					_tmp47__length1 = args_length1;
					yrcd_router_who_handler (self, _tmp46_, _tmp47_, _tmp47__length1);
					break;
				}
			}
		} else if (_tmp32_ == ((0 != _tmp31_label9) ? _tmp31_label9 : (_tmp31_label9 = g_quark_from_static_string ("part")))) {
			switch (0) {
				default:
				{
					yrcdUser* _tmp48_ = NULL;
					gchar** _tmp49_ = NULL;
					gint _tmp49__length1 = 0;
					_tmp48_ = user;
					_tmp49_ = args;
					_tmp49__length1 = args_length1;
					yrcd_router_part_handler (self, _tmp48_, _tmp49_, _tmp49__length1);
					break;
				}
			}
		} else {
			switch (0) {
				default:
				{
					yrcdUser* _tmp50_ = NULL;
					gchar** _tmp51_ = NULL;
					gint _tmp51__length1 = 0;
					_tmp50_ = user;
					_tmp51_ = args;
					_tmp51__length1 = args_length1;
					yrcd_router_unknown_command_handler (self, _tmp50_, _tmp51_, _tmp51__length1);
					break;
				}
			}
		}
	}
	args = (_vala_array_free (args, args_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (stripped);
}


void yrcd_router_part_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	yrcdUser* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GString* builder = NULL;
	GString* _tmp4_ = NULL;
	gchar* msg = NULL;
	gchar** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	yrcdChannel* chan = NULL;
	yrcdServer* _tmp17_ = NULL;
	gchar** _tmp18_ = NULL;
	gint _tmp18__length1 = 0;
	const gchar* _tmp19_ = NULL;
	yrcdChannel* _tmp20_ = NULL;
	yrcdUser* _tmp21_ = NULL;
	yrcdChannel* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = user;
	_tmp1_ = yrcd_user_get_registered (_tmp0_);
	_tmp2_ = _tmp1_;
	if (!_tmp2_) {
		yrcdUser* _tmp3_ = NULL;
		_tmp3_ = user;
		yrcd_user_fire_numeric (_tmp3_, YRCD_ERR_NOTREGISTERED, NULL);
		return;
	}
	_tmp4_ = g_string_new ("");
	builder = _tmp4_;
	_tmp5_ = args;
	_tmp5__length1 = args_length1;
	if (_tmp5__length1 > 2) {
		GString* _tmp6_ = NULL;
		gchar** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		GString* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		gboolean _tmp12_ = FALSE;
		GString* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		_tmp6_ = builder;
		_tmp7_ = args;
		_tmp7__length1 = args_length1;
		_tmp8_ = yrcd_router_assemble (self, 2, _tmp7_, _tmp7__length1);
		_tmp9_ = _tmp8_;
		g_string_append (_tmp6_, _tmp9_);
		_g_free0 (_tmp9_);
		_tmp10_ = builder;
		_tmp11_ = _tmp10_->str;
		_tmp12_ = g_str_has_prefix (_tmp11_, ":");
		if (_tmp12_) {
			GString* _tmp13_ = NULL;
			_tmp13_ = builder;
			g_string_erase (_tmp13_, (gssize) 0, (gssize) 1);
		}
		_tmp14_ = builder;
		_tmp15_ = _tmp14_->str;
		_tmp16_ = g_strdup (_tmp15_);
		_g_free0 (msg);
		msg = _tmp16_;
	} else {
		_g_free0 (msg);
		msg = NULL;
	}
	_tmp17_ = self->server;
	_tmp18_ = args;
	_tmp18__length1 = args_length1;
	_tmp19_ = _tmp18_[1];
	_tmp20_ = yrcd_server_get_channel_by_name (_tmp17_, _tmp19_);
	chan = _tmp20_;
	_tmp21_ = user;
	_tmp22_ = chan;
	_tmp23_ = msg;
	yrcd_user_part (_tmp21_, _tmp22_, _tmp23_);
	_g_object_unref0 (chan);
	_g_free0 (msg);
	_g_string_free0 (builder);
}


void yrcd_router_who_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	yrcdUser* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gint i = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = user;
	_tmp1_ = yrcd_user_get_registered (_tmp0_);
	_tmp2_ = _tmp1_;
	if (!_tmp2_) {
		yrcdUser* _tmp3_ = NULL;
		_tmp3_ = user;
		yrcd_user_fire_numeric (_tmp3_, YRCD_ERR_NOTREGISTERED, NULL);
		return;
	}
	{
		gboolean _tmp4_ = FALSE;
		i = 1;
		_tmp4_ = TRUE;
		while (TRUE) {
			gint _tmp6_ = 0;
			gchar** _tmp7_ = NULL;
			gint _tmp7__length1 = 0;
			yrcdChannel* chan = NULL;
			yrcdServer* _tmp8_ = NULL;
			gchar** _tmp9_ = NULL;
			gint _tmp9__length1 = 0;
			gint _tmp10_ = 0;
			const gchar* _tmp11_ = NULL;
			yrcdChannel* _tmp12_ = NULL;
			yrcdChannel* _tmp13_ = NULL;
			GList* _tmp14_ = NULL;
			guint _tmp15_ = 0U;
			if (!_tmp4_) {
				gint _tmp5_ = 0;
				_tmp5_ = i;
				i = _tmp5_ + 1;
			}
			_tmp4_ = FALSE;
			_tmp6_ = i;
			_tmp7_ = args;
			_tmp7__length1 = args_length1;
			if (!(_tmp6_ < _tmp7__length1)) {
				break;
			}
			_tmp8_ = self->server;
			_tmp9_ = args;
			_tmp9__length1 = args_length1;
			_tmp10_ = i;
			_tmp11_ = _tmp9_[_tmp10_];
			_tmp12_ = yrcd_server_get_channel_by_name (_tmp8_, _tmp11_);
			chan = _tmp12_;
			_tmp13_ = chan;
			_tmp14_ = _tmp13_->users;
			_tmp15_ = g_list_length (_tmp14_);
			if (_tmp15_ > ((guint) 0)) {
				yrcdChannel* _tmp16_ = NULL;
				yrcdUser* _tmp17_ = NULL;
				_tmp16_ = chan;
				_tmp17_ = user;
				yrcd_channel_who_response (_tmp16_, _tmp17_);
			}
			_g_object_unref0 (chan);
		}
	}
}


gchar* yrcd_router_assemble (yrcdRouter* self, gint position, gchar** args, int args_length1) {
	gchar* result = NULL;
	gint i = 0;
	GString* builder = NULL;
	GString* _tmp0_ = NULL;
	GString* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_string_new ("");
	builder = _tmp0_;
	{
		gint _tmp1_ = 0;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = position;
		i = _tmp1_;
		_tmp2_ = TRUE;
		while (TRUE) {
			gint _tmp4_ = 0;
			gchar** _tmp5_ = NULL;
			gint _tmp5__length1 = 0;
			GString* _tmp6_ = NULL;
			gchar** _tmp7_ = NULL;
			gint _tmp7__length1 = 0;
			gint _tmp8_ = 0;
			const gchar* _tmp9_ = NULL;
			GString* _tmp10_ = NULL;
			if (!_tmp2_) {
				gint _tmp3_ = 0;
				_tmp3_ = i;
				i = _tmp3_ + 1;
			}
			_tmp2_ = FALSE;
			_tmp4_ = i;
			_tmp5_ = args;
			_tmp5__length1 = args_length1;
			if (!(_tmp4_ < _tmp5__length1)) {
				break;
			}
			_tmp6_ = builder;
			_tmp7_ = args;
			_tmp7__length1 = args_length1;
			_tmp8_ = i;
			_tmp9_ = _tmp7_[_tmp8_];
			g_string_append (_tmp6_, _tmp9_);
			_tmp10_ = builder;
			g_string_append (_tmp10_, " ");
		}
	}
	_tmp11_ = builder;
	_tmp12_ = _tmp11_->str;
	_tmp13_ = string_strip (_tmp12_);
	result = _tmp13_;
	_g_string_free0 (builder);
	return result;
}


void yrcd_router_quit_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	if (_tmp0__length1 < 2) {
		yrcdUser* _tmp1_ = NULL;
		_tmp1_ = user;
		yrcd_user_quit (_tmp1_, NULL);
	} else {
		GString* builder = NULL;
		GString* _tmp2_ = NULL;
		GString* _tmp3_ = NULL;
		gchar** _tmp4_ = NULL;
		gint _tmp4__length1 = 0;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		GString* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gboolean _tmp9_ = FALSE;
		yrcdUser* _tmp11_ = NULL;
		GString* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		_tmp2_ = g_string_new ("");
		builder = _tmp2_;
		_tmp3_ = builder;
		_tmp4_ = args;
		_tmp4__length1 = args_length1;
		_tmp5_ = yrcd_router_assemble (self, 1, _tmp4_, _tmp4__length1);
		_tmp6_ = _tmp5_;
		g_string_append (_tmp3_, _tmp6_);
		_g_free0 (_tmp6_);
		_tmp7_ = builder;
		_tmp8_ = _tmp7_->str;
		_tmp9_ = g_str_has_prefix (_tmp8_, ":");
		if (_tmp9_) {
			GString* _tmp10_ = NULL;
			_tmp10_ = builder;
			g_string_erase (_tmp10_, (gssize) 0, (gssize) 1);
		}
		_tmp11_ = user;
		_tmp12_ = builder;
		_tmp13_ = _tmp12_->str;
		yrcd_user_quit (_tmp11_, _tmp13_);
		_g_string_free0 (builder);
	}
}


void yrcd_router_ping_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	yrcdUser* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = user;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = _tmp1_[1];
	_tmp3_ = g_strdup_printf ("PONG %s", _tmp2_);
	_tmp4_ = _tmp3_;
	yrcd_user_send_line (_tmp0_, _tmp4_, G_PRIORITY_DEFAULT);
	_g_free0 (_tmp4_);
}


void yrcd_router_unknown_command_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	yrcdUser* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = user;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = _tmp1_[0];
	yrcd_user_fire_numeric (_tmp0_, YRCD_ERR_UNKNOWNCOMMAND, _tmp2_, NULL);
}


void yrcd_router_join_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	yrcdUser* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gchar** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	const gchar* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	yrcdChannel* chan = NULL;
	yrcdServer* _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	const gchar* _tmp14_ = NULL;
	yrcdChannel* _tmp15_ = NULL;
	yrcdUser* _tmp16_ = NULL;
	yrcdChannel* _tmp17_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = user;
	_tmp1_ = yrcd_user_get_registered (_tmp0_);
	_tmp2_ = _tmp1_;
	if (!_tmp2_) {
		yrcdUser* _tmp3_ = NULL;
		_tmp3_ = user;
		yrcd_user_fire_numeric (_tmp3_, YRCD_ERR_NOTREGISTERED, NULL);
		return;
	}
	_tmp4_ = args;
	_tmp4__length1 = args_length1;
	if (_tmp4__length1 < 2) {
		yrcdUser* _tmp5_ = NULL;
		_tmp5_ = user;
		yrcd_user_fire_numeric (_tmp5_, YRCD_ERR_NEEDMOREPARAMS, "JOIN", NULL);
		return;
	}
	_tmp6_ = args;
	_tmp6__length1 = args_length1;
	_tmp7_ = _tmp6_[1];
	_tmp8_ = yrcd_router_valid_chan_name (self, _tmp7_);
	if (!_tmp8_) {
		yrcdUser* _tmp9_ = NULL;
		gchar** _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		const gchar* _tmp11_ = NULL;
		_tmp9_ = user;
		_tmp10_ = args;
		_tmp10__length1 = args_length1;
		_tmp11_ = _tmp10_[1];
		yrcd_user_fire_numeric (_tmp9_, YRCD_ERR_NOSUCHCHANNEL, _tmp11_, NULL);
		return;
	}
	_tmp12_ = self->server;
	_tmp13_ = args;
	_tmp13__length1 = args_length1;
	_tmp14_ = _tmp13_[1];
	_tmp15_ = yrcd_server_get_channel_by_name (_tmp12_, _tmp14_);
	chan = _tmp15_;
	_tmp16_ = user;
	_tmp17_ = chan;
	yrcd_user_join (_tmp16_, _tmp17_);
	_g_object_unref0 (chan);
}


void yrcd_router_privmsg_handler (yrcdRouter* self, yrcdUser* user, gchar** args, int args_length1) {
	yrcdUser* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (user != NULL);
	_tmp0_ = user;
	_tmp1_ = yrcd_user_get_registered (_tmp0_);
	_tmp2_ = _tmp1_;
	if (!_tmp2_) {
		yrcdUser* _tmp3_ = NULL;
		_tmp3_ = user;
		yrcd_user_fire_numeric (_tmp3_, YRCD_ERR_NOTREGISTERED, NULL);
		return;
	}
	_tmp4_ = args;
	_tmp4__length1 = args_length1;
	if (_tmp4__length1 < 2) {
	} else {
		gchar** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		_tmp5_ = args;
		_tmp5__length1 = args_length1;
		if (_tmp5__length1 < 3) {
		} else {
			gchar** _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			const gchar* _tmp7_ = NULL;
			gboolean _tmp8_ = FALSE;
			yrcdServer* _tmp33_ = NULL;
			_tmp6_ = args;
			_tmp6__length1 = args_length1;
			_tmp7_ = _tmp6_[1];
			_tmp8_ = yrcd_router_valid_chan_name (self, _tmp7_);
			if (_tmp8_) {
				GString* builder = NULL;
				GString* _tmp9_ = NULL;
				gint i = 0;
				GString* _tmp19_ = NULL;
				const gchar* _tmp20_ = NULL;
				gboolean _tmp21_ = FALSE;
				gchar* msg = NULL;
				GString* _tmp23_ = NULL;
				const gchar* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
				yrcdChannel* chan = NULL;
				yrcdServer* _tmp26_ = NULL;
				gchar** _tmp27_ = NULL;
				gint _tmp27__length1 = 0;
				const gchar* _tmp28_ = NULL;
				yrcdChannel* _tmp29_ = NULL;
				yrcdChannel* _tmp30_ = NULL;
				yrcdUser* _tmp31_ = NULL;
				const gchar* _tmp32_ = NULL;
				_tmp9_ = g_string_new ("");
				builder = _tmp9_;
				{
					gboolean _tmp10_ = FALSE;
					i = 2;
					_tmp10_ = TRUE;
					while (TRUE) {
						gint _tmp12_ = 0;
						gchar** _tmp13_ = NULL;
						gint _tmp13__length1 = 0;
						GString* _tmp14_ = NULL;
						gchar** _tmp15_ = NULL;
						gint _tmp15__length1 = 0;
						gint _tmp16_ = 0;
						const gchar* _tmp17_ = NULL;
						GString* _tmp18_ = NULL;
						if (!_tmp10_) {
							gint _tmp11_ = 0;
							_tmp11_ = i;
							i = _tmp11_ + 1;
						}
						_tmp10_ = FALSE;
						_tmp12_ = i;
						_tmp13_ = args;
						_tmp13__length1 = args_length1;
						if (!(_tmp12_ < _tmp13__length1)) {
							break;
						}
						_tmp14_ = builder;
						_tmp15_ = args;
						_tmp15__length1 = args_length1;
						_tmp16_ = i;
						_tmp17_ = _tmp15_[_tmp16_];
						g_string_append (_tmp14_, _tmp17_);
						_tmp18_ = builder;
						g_string_append (_tmp18_, " ");
					}
				}
				_tmp19_ = builder;
				_tmp20_ = _tmp19_->str;
				_tmp21_ = g_str_has_prefix (_tmp20_, ":");
				if (_tmp21_) {
					GString* _tmp22_ = NULL;
					_tmp22_ = builder;
					g_string_erase (_tmp22_, (gssize) 0, (gssize) 1);
				}
				_tmp23_ = builder;
				_tmp24_ = _tmp23_->str;
				_tmp25_ = string_strip (_tmp24_);
				msg = _tmp25_;
				_tmp26_ = self->server;
				_tmp27_ = args;
				_tmp27__length1 = args_length1;
				_tmp28_ = _tmp27_[1];
				_tmp29_ = yrcd_server_get_channel_by_name (_tmp26_, _tmp28_);
				chan = _tmp29_;
				_tmp30_ = chan;
				_tmp31_ = user;
				_tmp32_ = msg;
				yrcd_channel_privmsg (_tmp30_, _tmp31_, _tmp32_);
				_g_object_unref0 (chan);
				_g_free0 (msg);
				_g_string_free0 (builder);
			}
			_tmp33_ = self->server;
			if (yrcd_server_get_user_by_nick == NULL) {
			}
			return;
		}
	}
}


static void yrcd_router_process_user_data_free (gpointer _data) {
	YrcdRouterProcessUserData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->conn);
	_g_object_unref0 (_data_->self);
	g_slice_free (YrcdRouterProcessUserData, _data_);
}


void yrcd_router_process_user (yrcdRouter* self, GSocketConnection* conn, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	YrcdRouterProcessUserData* _data_;
	yrcdRouter* _tmp0_ = NULL;
	GSocketConnection* _tmp1_ = NULL;
	GSocketConnection* _tmp2_ = NULL;
	_data_ = g_slice_new0 (YrcdRouterProcessUserData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, yrcd_router_process_user);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, yrcd_router_process_user_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = conn;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_g_object_unref0 (_data_->conn);
	_data_->conn = _tmp2_;
	yrcd_router_process_user_co (_data_);
}


void yrcd_router_process_user_finish (yrcdRouter* self, GAsyncResult* _res_) {
	YrcdRouterProcessUserData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void yrcd_router_process_user_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	YrcdRouterProcessUserData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	yrcd_router_process_user_co (_data_);
}


static gboolean yrcd_router_process_user_co (YrcdRouterProcessUserData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = _data_->self->server;
	_data_->_tmp2_ = NULL;
	_data_->_tmp2_ = _data_->_tmp1_->userlist;
	_data_->_tmp3_ = 0;
	_data_->_tmp3_ = gee_abstract_map_get_size ((GeeMap*) _data_->_tmp2_);
	_data_->_tmp4_ = 0;
	_data_->_tmp4_ = _data_->_tmp3_;
	_data_->_tmp5_ = NULL;
	_data_->_tmp5_ = _data_->self->server;
	_data_->_tmp6_ = NULL;
	_data_->_tmp6_ = _data_->_tmp5_->config;
	_data_->_tmp7_ = 0;
	_data_->_tmp7_ = _data_->_tmp6_->max_users;
	if (_data_->_tmp4_ > _data_->_tmp7_) {
		_data_->_tmp8_ = NULL;
		_data_->_tmp8_ = _data_->self->server;
		_data_->_tmp9_ = NULL;
		_data_->_tmp9_ = _data_->_tmp8_->config;
		_data_->_tmp10_ = 0;
		_data_->_tmp10_ = _data_->_tmp9_->max_users;
		_data_->_tmp0_ = _data_->_tmp10_ > 0;
	} else {
		_data_->_tmp0_ = FALSE;
	}
	if (_data_->_tmp0_) {
		{
			_data_->_tmp11_ = NULL;
			_data_->_tmp11_ = _data_->conn;
			_data_->_tmp12_ = NULL;
			_data_->_tmp12_ = g_socket_connection_get_socket (_data_->_tmp11_);
			g_socket_close (_data_->_tmp12_, &_data_->_inner_error_);
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
				goto __catch1_g_error;
			}
		}
		goto __finally1;
		__catch1_g_error:
		{
			_data_->e = _data_->_inner_error_;
			_data_->_inner_error_ = NULL;
			_data_->_tmp13_ = NULL;
			_data_->_tmp13_ = _data_->self->server;
			_data_->_tmp14_ = NULL;
			_data_->_tmp14_ = _data_->e;
			_data_->_tmp15_ = NULL;
			_data_->_tmp15_ = _data_->_tmp14_->message;
			yrcd_server_log (_data_->_tmp13_, _data_->_tmp15_);
			_g_error_free0 (_data_->e);
		}
		__finally1:
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
			g_clear_error (&_data_->_inner_error_);
			return FALSE;
		}
		_data_->_tmp16_ = NULL;
		_data_->_tmp16_ = _data_->self->server;
		_data_->_tmp17_ = NULL;
		_data_->_tmp17_ = _data_->self->server;
		_data_->_tmp18_ = NULL;
		_data_->_tmp18_ = _data_->_tmp17_->config;
		_data_->_tmp19_ = 0;
		_data_->_tmp19_ = _data_->_tmp18_->max_users;
		_data_->_tmp20_ = NULL;
		_data_->_tmp20_ = g_strdup_printf ("Max amount of connections %d reached, closing socket", _data_->_tmp19_);
		_data_->_tmp21_ = NULL;
		_data_->_tmp21_ = _data_->_tmp20_;
		yrcd_server_log (_data_->_tmp16_, _data_->_tmp21_);
		_g_free0 (_data_->_tmp21_);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp22_ = NULL;
	_data_->_tmp22_ = _data_->conn;
	_data_->_tmp23_ = NULL;
	_data_->_tmp23_ = _data_->self->server;
	_data_->_tmp24_ = NULL;
	_data_->_tmp24_ = yrcd_user_new (_data_->_tmp22_, _data_->_tmp23_);
	_data_->user = _data_->_tmp24_;
	_data_->_tmp25_ = NULL;
	_data_->_tmp25_ = _data_->self->server;
	_data_->_tmp26_ = NULL;
	_data_->_tmp26_ = _data_->_tmp25_->userlist;
	_data_->_tmp27_ = NULL;
	_data_->_tmp27_ = _data_->user;
	_data_->_tmp28_ = 0;
	_data_->_tmp28_ = yrcd_user_get_id (_data_->_tmp27_);
	_data_->_tmp29_ = 0;
	_data_->_tmp29_ = _data_->_tmp28_;
	_data_->_tmp30_ = NULL;
	_data_->_tmp30_ = _data_->user;
	gee_abstract_map_set ((GeeAbstractMap*) _data_->_tmp26_, (gpointer) ((gintptr) _data_->_tmp29_), _data_->_tmp30_);
	_data_->_tmp31_ = NULL;
	_data_->_tmp31_ = _data_->self->server;
	_data_->_tmp32_ = NULL;
	_data_->_tmp32_ = _data_->_tmp31_->userlist;
	_data_->_tmp33_ = 0;
	_data_->_tmp33_ = gee_abstract_map_get_size ((GeeMap*) _data_->_tmp32_);
	_data_->_tmp34_ = 0;
	_data_->_tmp34_ = _data_->_tmp33_;
	_data_->_tmp35_ = NULL;
	_data_->_tmp35_ = _data_->self->server;
	_data_->_tmp36_ = 0;
	_data_->_tmp36_ = _data_->_tmp35_->max_users;
	if (_data_->_tmp34_ > _data_->_tmp36_) {
		_data_->_tmp37_ = NULL;
		_data_->_tmp37_ = _data_->self->server;
		_data_->_tmp38_ = NULL;
		_data_->_tmp38_ = _data_->self->server;
		_data_->_tmp39_ = NULL;
		_data_->_tmp39_ = _data_->_tmp38_->userlist;
		_data_->_tmp40_ = 0;
		_data_->_tmp40_ = gee_abstract_map_get_size ((GeeMap*) _data_->_tmp39_);
		_data_->_tmp41_ = 0;
		_data_->_tmp41_ = _data_->_tmp40_;
		_data_->_tmp37_->max_users = _data_->_tmp41_;
		_data_->_tmp42_ = NULL;
		_data_->_tmp42_ = _data_->self->server;
		_data_->_tmp43_ = NULL;
		_data_->_tmp43_ = _data_->self->server;
		_data_->_tmp44_ = 0;
		_data_->_tmp44_ = _data_->_tmp43_->max_users;
		_data_->_tmp45_ = NULL;
		_data_->_tmp45_ = g_strdup_printf ("New max amount of users: %d", _data_->_tmp44_);
		_data_->_tmp46_ = NULL;
		_data_->_tmp46_ = _data_->_tmp45_;
		yrcd_server_log (_data_->_tmp42_, _data_->_tmp46_);
		_g_free0 (_data_->_tmp46_);
	}
	_data_->_tmp47_ = NULL;
	_data_->_tmp47_ = _data_->user;
	_data_->_tmp48_ = NULL;
	_data_->_tmp48_ = yrcd_user_get_sock (_data_->_tmp47_);
	_data_->_tmp49_ = NULL;
	_data_->_tmp49_ = _data_->_tmp48_;
	_data_->_tmp50_ = NULL;
	_data_->_tmp50_ = g_socket_connection_get_socket (_data_->_tmp49_);
	_data_->_tmp51_ = NULL;
	_data_->_tmp51_ = _g_object_ref0 (_data_->_tmp50_);
	_data_->socket = _data_->_tmp51_;
	while (TRUE) {
		_data_->_tmp52_ = NULL;
		_data_->_tmp52_ = _data_->socket;
		_data_->_tmp53_ = FALSE;
		_data_->_tmp53_ = g_socket_is_connected (_data_->_tmp52_);
		if (!_data_->_tmp53_) {
			break;
		}
		{
			_data_->_tmp54_ = NULL;
			_data_->_tmp54_ = _data_->user;
			_data_->_tmp55_ = NULL;
			_data_->_tmp55_ = yrcd_user_get_dis (_data_->_tmp54_);
			_data_->_tmp56_ = NULL;
			_data_->_tmp56_ = _data_->_tmp55_;
			_data_->_state_ = 1;
			g_data_input_stream_read_line_async (_data_->_tmp56_, G_PRIORITY_DEFAULT, NULL, yrcd_router_process_user_ready, _data_);
			return FALSE;
			_state_1:
			_data_->_tmp57_ = NULL;
			_data_->_tmp57_ = g_data_input_stream_read_line_finish (_data_->_tmp56_, _data_->_res_, NULL, &_data_->_inner_error_);
			_data_->msg = _data_->_tmp57_;
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
				goto __catch2_g_error;
			}
			_data_->_tmp58_ = NULL;
			_data_->_tmp58_ = _data_->user;
			_data_->_tmp59_ = NULL;
			_data_->_tmp59_ = _data_->msg;
			yrcd_router_route (_data_->self, _data_->_tmp58_, _data_->_tmp59_);
			_g_free0 (_data_->msg);
		}
		goto __finally2;
		__catch2_g_error:
		{
			_data_->_vala1_e = _data_->_inner_error_;
			_data_->_inner_error_ = NULL;
			_data_->_tmp60_ = NULL;
			_data_->_tmp60_ = _data_->self->server;
			_data_->_tmp61_ = NULL;
			_data_->_tmp61_ = _data_->_vala1_e;
			_data_->_tmp62_ = NULL;
			_data_->_tmp62_ = _data_->_tmp61_->message;
			_data_->_tmp63_ = NULL;
			_data_->_tmp63_ = g_strdup_printf ("Encountered error reading socket: %s", _data_->_tmp62_);
			_data_->_tmp64_ = NULL;
			_data_->_tmp64_ = _data_->_tmp63_;
			yrcd_server_log (_data_->_tmp60_, _data_->_tmp64_);
			_g_free0 (_data_->_tmp64_);
			_data_->_tmp65_ = NULL;
			_data_->_tmp65_ = _data_->user;
			yrcd_user_quit (_data_->_tmp65_, NULL);
			_g_error_free0 (_data_->_vala1_e);
			_g_object_unref0 (_data_->socket);
			_g_object_unref0 (_data_->user);
			if (_data_->_state_ == 0) {
				g_simple_async_result_complete_in_idle (_data_->_async_result);
			} else {
				g_simple_async_result_complete (_data_->_async_result);
			}
			g_object_unref (_data_->_async_result);
			return FALSE;
		}
		__finally2:
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
			_g_object_unref0 (_data_->socket);
			_g_object_unref0 (_data_->user);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
			g_clear_error (&_data_->_inner_error_);
			return FALSE;
		}
	}
	_g_object_unref0 (_data_->socket);
	_g_object_unref0 (_data_->user);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


gboolean yrcd_router_valid_chan_name (yrcdRouter* self, const gchar* chan) {
	gboolean result = FALSE;
	gboolean valid = FALSE;
	gboolean has_prefix = FALSE;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp23_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (chan != NULL, FALSE);
	valid = TRUE;
	has_prefix = FALSE;
	{
		const gchar** k_collection = NULL;
		gint k_collection_length1 = 0;
		gint _k_collection_size_ = 0;
		gint k_it = 0;
		k_collection = YRCD_CONSTANTS_chan_prefixes;
		k_collection_length1 = G_N_ELEMENTS (YRCD_CONSTANTS_chan_prefixes);
		for (k_it = 0; k_it < G_N_ELEMENTS (YRCD_CONSTANTS_chan_prefixes); k_it = k_it + 1) {
			gchar* _tmp0_ = NULL;
			gchar* k = NULL;
			_tmp0_ = g_strdup (k_collection[k_it]);
			k = _tmp0_;
			{
				const gchar* _tmp1_ = NULL;
				const gchar* _tmp2_ = NULL;
				gboolean _tmp3_ = FALSE;
				_tmp1_ = chan;
				_tmp2_ = k;
				_tmp3_ = g_str_has_prefix (_tmp1_, _tmp2_);
				if (_tmp3_) {
					yrcdServer* _tmp4_ = NULL;
					const gchar* _tmp5_ = NULL;
					const gchar* _tmp6_ = NULL;
					const gchar* _tmp7_ = NULL;
					const gchar* _tmp8_ = NULL;
					gchar* _tmp9_ = NULL;
					gchar* _tmp10_ = NULL;
					_tmp4_ = self->server;
					_tmp5_ = chan;
					_tmp6_ = string_to_string (_tmp5_);
					_tmp7_ = k;
					_tmp8_ = string_to_string (_tmp7_);
					_tmp9_ = g_strconcat ("channel name ", _tmp6_, " has valid prefix ", _tmp8_, NULL);
					_tmp10_ = _tmp9_;
					yrcd_server_log (_tmp4_, _tmp10_);
					_g_free0 (_tmp10_);
					has_prefix = TRUE;
					_g_free0 (k);
					break;
				}
				_g_free0 (k);
			}
		}
	}
	{
		const gchar** k_collection = NULL;
		gint k_collection_length1 = 0;
		gint _k_collection_size_ = 0;
		gint k_it = 0;
		k_collection = YRCD_CONSTANTS_chan_forbidden;
		k_collection_length1 = G_N_ELEMENTS (YRCD_CONSTANTS_chan_forbidden);
		for (k_it = 0; k_it < G_N_ELEMENTS (YRCD_CONSTANTS_chan_forbidden); k_it = k_it + 1) {
			gchar* _tmp11_ = NULL;
			gchar* k = NULL;
			_tmp11_ = g_strdup (k_collection[k_it]);
			k = _tmp11_;
			{
				const gchar* _tmp12_ = NULL;
				const gchar* _tmp13_ = NULL;
				gboolean _tmp14_ = FALSE;
				_tmp12_ = chan;
				_tmp13_ = k;
				_tmp14_ = string_contains (_tmp12_, _tmp13_);
				if (_tmp14_) {
					yrcdServer* _tmp15_ = NULL;
					const gchar* _tmp16_ = NULL;
					const gchar* _tmp17_ = NULL;
					const gchar* _tmp18_ = NULL;
					const gchar* _tmp19_ = NULL;
					gchar* _tmp20_ = NULL;
					gchar* _tmp21_ = NULL;
					_tmp15_ = self->server;
					_tmp16_ = chan;
					_tmp17_ = string_to_string (_tmp16_);
					_tmp18_ = k;
					_tmp19_ = string_to_string (_tmp18_);
					_tmp20_ = g_strconcat ("channel name ", _tmp17_, " has invalid char ", _tmp19_, NULL);
					_tmp21_ = _tmp20_;
					yrcd_server_log (_tmp15_, _tmp21_);
					_g_free0 (_tmp21_);
					valid = FALSE;
					_g_free0 (k);
					break;
				}
				_g_free0 (k);
			}
		}
	}
	_tmp23_ = has_prefix;
	if (_tmp23_) {
		gboolean _tmp24_ = FALSE;
		_tmp24_ = valid;
		_tmp22_ = _tmp24_;
	} else {
		_tmp22_ = FALSE;
	}
	if (_tmp22_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}


static void yrcd_router_class_init (yrcdRouterClass * klass) {
	yrcd_router_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = yrcd_router_finalize;
}


static void yrcd_router_instance_init (yrcdRouter * self) {
}


static void yrcd_router_finalize (GObject* obj) {
	yrcdRouter * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_ROUTER, yrcdRouter);
	_g_object_unref0 (self->server);
	G_OBJECT_CLASS (yrcd_router_parent_class)->finalize (obj);
}


GType yrcd_router_get_type (void) {
	static volatile gsize yrcd_router_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_router_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdRouterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_router_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdRouter), 0, (GInstanceInitFunc) yrcd_router_instance_init, NULL };
		GType yrcd_router_type_id;
		yrcd_router_type_id = g_type_register_static (YRCD_TYPE_BASE_OBJECT, "yrcdRouter", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_router_type_id__volatile, yrcd_router_type_id);
	}
	return yrcd_router_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



