/* user.c generated by valac 0.24.0, the Vala compiler
 * generated from user.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define YRCD_TYPE_YRCD_USER (yrcd_yrcd_user_get_type ())
#define YRCD_YRCD_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_USER, yrcdyrcd_user))
#define YRCD_YRCD_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_USER, yrcdyrcd_userClass))
#define YRCD_IS_YRCD_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_USER))
#define YRCD_IS_YRCD_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_USER))
#define YRCD_YRCD_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_USER, yrcdyrcd_userClass))

typedef struct _yrcdyrcd_user yrcdyrcd_user;
typedef struct _yrcdyrcd_userClass yrcdyrcd_userClass;
typedef struct _yrcdyrcd_userPrivate yrcdyrcd_userPrivate;

#define YRCD_TYPE_YRCD_SERVER (yrcd_yrcd_server_get_type ())
#define YRCD_YRCD_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_SERVER, yrcdyrcd_server))
#define YRCD_YRCD_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_SERVER, yrcdyrcd_serverClass))
#define YRCD_IS_YRCD_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_SERVER))
#define YRCD_IS_YRCD_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_SERVER))
#define YRCD_YRCD_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_SERVER, yrcdyrcd_serverClass))

typedef struct _yrcdyrcd_server yrcdyrcd_server;
typedef struct _yrcdyrcd_serverClass yrcdyrcd_serverClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _yrcdyrcd_user {
	GObject parent_instance;
	yrcdyrcd_userPrivate * priv;
};

struct _yrcdyrcd_userClass {
	GObjectClass parent_class;
};

struct _yrcdyrcd_userPrivate {
	GSocketConnection* _sock;
	GDataInputStream* _dis;
	GDataOutputStream* _dos;
	yrcdyrcd_server* _server;
	gint _id;
};


static gpointer yrcd_yrcd_user_parent_class = NULL;

GType yrcd_yrcd_user_get_type (void) G_GNUC_CONST;
GType yrcd_yrcd_server_get_type (void) G_GNUC_CONST;
#define YRCD_YRCD_USER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), YRCD_TYPE_YRCD_USER, yrcdyrcd_userPrivate))
enum  {
	YRCD_YRCD_USER_DUMMY_PROPERTY,
	YRCD_YRCD_USER_SOCK,
	YRCD_YRCD_USER_DIS,
	YRCD_YRCD_USER_DOS,
	YRCD_YRCD_USER_SERVER,
	YRCD_YRCD_USER_ID
};
yrcdyrcd_user* yrcd_yrcd_user_new (GSocketConnection* conn, yrcdyrcd_server* _server);
yrcdyrcd_user* yrcd_yrcd_user_construct (GType object_type, GSocketConnection* conn, yrcdyrcd_server* _server);
void yrcd_yrcd_user_set_sock (yrcdyrcd_user* self, GSocketConnection* value);
void yrcd_yrcd_user_set_server (yrcdyrcd_user* self, yrcdyrcd_server* value);
yrcdyrcd_server* yrcd_yrcd_user_get_server (yrcdyrcd_user* self);
void yrcd_yrcd_server_log (yrcdyrcd_server* self, const gchar* msg);
GSocketConnection* yrcd_yrcd_user_get_sock (yrcdyrcd_user* self);
void yrcd_yrcd_user_set_dis (yrcdyrcd_user* self, GDataInputStream* value);
void yrcd_yrcd_user_set_dos (yrcdyrcd_user* self, GDataOutputStream* value);
gint yrcd_yrcd_server_new_userid (yrcdyrcd_server* self);
void yrcd_yrcd_user_set_id (yrcdyrcd_user* self, gint value);
gint yrcd_yrcd_user_get_id (yrcdyrcd_user* self);
void yrcd_yrcd_user_quit (yrcdyrcd_user* self, const gchar* msg);
GDataInputStream* yrcd_yrcd_user_get_dis (yrcdyrcd_user* self);
GDataOutputStream* yrcd_yrcd_user_get_dos (yrcdyrcd_user* self);
static void yrcd_yrcd_user_finalize (GObject* obj);
static void _vala_yrcd_yrcd_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_yrcd_yrcd_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


yrcdyrcd_user* yrcd_yrcd_user_construct (GType object_type, GSocketConnection* conn, yrcdyrcd_server* _server) {
	yrcdyrcd_user * self = NULL;
	GSocketConnection* _tmp0_ = NULL;
	yrcdyrcd_server* _tmp1_ = NULL;
	yrcdyrcd_server* _tmp2_ = NULL;
	GSocketConnection* _tmp3_ = NULL;
	GInputStream* _tmp4_ = NULL;
	GInputStream* _tmp5_ = NULL;
	GDataInputStream* _tmp6_ = NULL;
	GDataInputStream* _tmp7_ = NULL;
	GSocketConnection* _tmp8_ = NULL;
	GOutputStream* _tmp9_ = NULL;
	GOutputStream* _tmp10_ = NULL;
	GDataOutputStream* _tmp11_ = NULL;
	GDataOutputStream* _tmp12_ = NULL;
	yrcdyrcd_server* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	yrcdyrcd_server* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	g_return_val_if_fail (conn != NULL, NULL);
	g_return_val_if_fail (_server != NULL, NULL);
	self = (yrcdyrcd_user*) g_object_new (object_type, NULL);
	_tmp0_ = conn;
	yrcd_yrcd_user_set_sock (self, _tmp0_);
	_tmp1_ = _server;
	yrcd_yrcd_user_set_server (self, _tmp1_);
	_tmp2_ = self->priv->_server;
	yrcd_yrcd_server_log (_tmp2_, "User constructor called, opening data streams");
	_tmp3_ = self->priv->_sock;
	_tmp4_ = g_io_stream_get_input_stream ((GIOStream*) _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_data_input_stream_new (_tmp5_);
	_tmp7_ = _tmp6_;
	yrcd_yrcd_user_set_dis (self, _tmp7_);
	_g_object_unref0 (_tmp7_);
	_tmp8_ = self->priv->_sock;
	_tmp9_ = g_io_stream_get_output_stream ((GIOStream*) _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_data_output_stream_new (_tmp10_);
	_tmp12_ = _tmp11_;
	yrcd_yrcd_user_set_dos (self, _tmp12_);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = self->priv->_server;
	_tmp14_ = yrcd_yrcd_server_new_userid (_tmp13_);
	yrcd_yrcd_user_set_id (self, _tmp14_);
	_tmp15_ = self->priv->_server;
	_tmp16_ = self->priv->_id;
	_tmp17_ = g_strdup_printf ("User registered with ID %d", _tmp16_);
	_tmp18_ = _tmp17_;
	yrcd_yrcd_server_log (_tmp15_, _tmp18_);
	_g_free0 (_tmp18_);
	return self;
}


yrcdyrcd_user* yrcd_yrcd_user_new (GSocketConnection* conn, yrcdyrcd_server* _server) {
	return yrcd_yrcd_user_construct (YRCD_TYPE_YRCD_USER, conn, _server);
}


void yrcd_yrcd_user_quit (yrcdyrcd_user* self, const gchar* msg) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GSocketConnection* _tmp0_ = NULL;
		GSocket* _tmp1_ = NULL;
		_tmp0_ = self->priv->_sock;
		_tmp1_ = g_socket_connection_get_socket (_tmp0_);
		g_socket_close (_tmp1_, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		yrcdyrcd_server* _tmp2_ = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = self->priv->_server;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		_tmp5_ = g_strdup_printf ("Error closing socket: %s", _tmp4_);
		_tmp6_ = _tmp5_;
		yrcd_yrcd_server_log (_tmp2_, _tmp6_);
		_g_free0 (_tmp6_);
		_g_error_free0 (e);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


GSocketConnection* yrcd_yrcd_user_get_sock (yrcdyrcd_user* self) {
	GSocketConnection* result;
	GSocketConnection* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_sock;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void yrcd_yrcd_user_set_sock (yrcdyrcd_user* self, GSocketConnection* value) {
	GSocketConnection* _tmp0_ = NULL;
	GSocketConnection* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_sock);
	self->priv->_sock = _tmp1_;
	g_object_notify ((GObject *) self, "sock");
}


GDataInputStream* yrcd_yrcd_user_get_dis (yrcdyrcd_user* self) {
	GDataInputStream* result;
	GDataInputStream* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_dis;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_dis (yrcdyrcd_user* self, GDataInputStream* value) {
	GDataInputStream* _tmp0_ = NULL;
	GDataInputStream* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_dis);
	self->priv->_dis = _tmp1_;
	g_object_notify ((GObject *) self, "dis");
}


GDataOutputStream* yrcd_yrcd_user_get_dos (yrcdyrcd_user* self) {
	GDataOutputStream* result;
	GDataOutputStream* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_dos;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_dos (yrcdyrcd_user* self, GDataOutputStream* value) {
	GDataOutputStream* _tmp0_ = NULL;
	GDataOutputStream* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_dos);
	self->priv->_dos = _tmp1_;
	g_object_notify ((GObject *) self, "dos");
}


yrcdyrcd_server* yrcd_yrcd_user_get_server (yrcdyrcd_user* self) {
	yrcdyrcd_server* result;
	yrcdyrcd_server* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_server;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_server (yrcdyrcd_user* self, yrcdyrcd_server* value) {
	yrcdyrcd_server* _tmp0_ = NULL;
	yrcdyrcd_server* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_server);
	self->priv->_server = _tmp1_;
	g_object_notify ((GObject *) self, "server");
}


gint yrcd_yrcd_user_get_id (yrcdyrcd_user* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_id (yrcdyrcd_user* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_id = _tmp0_;
	g_object_notify ((GObject *) self, "id");
}


static void yrcd_yrcd_user_class_init (yrcdyrcd_userClass * klass) {
	yrcd_yrcd_user_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (yrcdyrcd_userPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_yrcd_yrcd_user_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_yrcd_yrcd_user_set_property;
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_user_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_SOCK, g_param_spec_object ("sock", "sock", "sock", G_TYPE_SOCKET_CONNECTION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_DIS, g_param_spec_object ("dis", "dis", "dis", G_TYPE_DATA_INPUT_STREAM, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_DOS, g_param_spec_object ("dos", "dos", "dos", g_data_output_stream_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_SERVER, g_param_spec_object ("server", "server", "server", YRCD_TYPE_YRCD_SERVER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_ID, g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void yrcd_yrcd_user_instance_init (yrcdyrcd_user * self) {
	self->priv = YRCD_YRCD_USER_GET_PRIVATE (self);
}


static void yrcd_yrcd_user_finalize (GObject* obj) {
	yrcdyrcd_user * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_USER, yrcdyrcd_user);
	_g_object_unref0 (self->priv->_sock);
	_g_object_unref0 (self->priv->_dis);
	_g_object_unref0 (self->priv->_dos);
	_g_object_unref0 (self->priv->_server);
	G_OBJECT_CLASS (yrcd_yrcd_user_parent_class)->finalize (obj);
}


GType yrcd_yrcd_user_get_type (void) {
	static volatile gsize yrcd_yrcd_user_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_user_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_userClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_user), 0, (GInstanceInitFunc) yrcd_yrcd_user_instance_init, NULL };
		GType yrcd_yrcd_user_type_id;
		yrcd_yrcd_user_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_user", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_user_type_id__volatile, yrcd_yrcd_user_type_id);
	}
	return yrcd_yrcd_user_type_id__volatile;
}


static void _vala_yrcd_yrcd_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	yrcdyrcd_user * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_USER, yrcdyrcd_user);
	switch (property_id) {
		case YRCD_YRCD_USER_SOCK:
		g_value_set_object (value, yrcd_yrcd_user_get_sock (self));
		break;
		case YRCD_YRCD_USER_DIS:
		g_value_set_object (value, yrcd_yrcd_user_get_dis (self));
		break;
		case YRCD_YRCD_USER_DOS:
		g_value_set_object (value, yrcd_yrcd_user_get_dos (self));
		break;
		case YRCD_YRCD_USER_SERVER:
		g_value_set_object (value, yrcd_yrcd_user_get_server (self));
		break;
		case YRCD_YRCD_USER_ID:
		g_value_set_int (value, yrcd_yrcd_user_get_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_yrcd_yrcd_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	yrcdyrcd_user * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_USER, yrcdyrcd_user);
	switch (property_id) {
		case YRCD_YRCD_USER_SOCK:
		yrcd_yrcd_user_set_sock (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_DIS:
		yrcd_yrcd_user_set_dis (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_DOS:
		yrcd_yrcd_user_set_dos (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_SERVER:
		yrcd_yrcd_user_set_server (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_ID:
		yrcd_yrcd_user_set_id (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



