/* user.c generated by valac 0.24.0, the Vala compiler
 * generated from user.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>
#include <stdarg.h>


#define YRCD_TYPE_YRCD_USER (yrcd_yrcd_user_get_type ())
#define YRCD_YRCD_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_USER, yrcdyrcd_user))
#define YRCD_YRCD_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_USER, yrcdyrcd_userClass))
#define YRCD_IS_YRCD_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_USER))
#define YRCD_IS_YRCD_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_USER))
#define YRCD_YRCD_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_USER, yrcdyrcd_userClass))

typedef struct _yrcdyrcd_user yrcdyrcd_user;
typedef struct _yrcdyrcd_userClass yrcdyrcd_userClass;
typedef struct _yrcdyrcd_userPrivate yrcdyrcd_userPrivate;

#define YRCD_TYPE_YRCD_CHANNEL (yrcd_yrcd_channel_get_type ())
#define YRCD_YRCD_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channel))
#define YRCD_YRCD_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channelClass))
#define YRCD_IS_YRCD_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_CHANNEL))
#define YRCD_IS_YRCD_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_CHANNEL))
#define YRCD_YRCD_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_CHANNEL, yrcdyrcd_channelClass))

typedef struct _yrcdyrcd_channel yrcdyrcd_channel;
typedef struct _yrcdyrcd_channelClass yrcdyrcd_channelClass;

#define YRCD_TYPE_YRCD_SERVER (yrcd_yrcd_server_get_type ())
#define YRCD_YRCD_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_SERVER, yrcdyrcd_server))
#define YRCD_YRCD_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_SERVER, yrcdyrcd_serverClass))
#define YRCD_IS_YRCD_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_SERVER))
#define YRCD_IS_YRCD_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_SERVER))
#define YRCD_YRCD_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_SERVER, yrcdyrcd_serverClass))

typedef struct _yrcdyrcd_server yrcdyrcd_server;
typedef struct _yrcdyrcd_serverClass yrcdyrcd_serverClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
typedef struct _yrcdyrcd_serverPrivate yrcdyrcd_serverPrivate;

#define YRCD_TYPE_YRCD_NUMERIC_WRAPPER (yrcd_yrcd_numeric_wrapper_get_type ())
#define YRCD_YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapper))
#define YRCD_YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapperClass))
#define YRCD_IS_YRCD_NUMERIC_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER))
#define YRCD_IS_YRCD_NUMERIC_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_YRCD_NUMERIC_WRAPPER))
#define YRCD_YRCD_NUMERIC_WRAPPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_YRCD_NUMERIC_WRAPPER, yrcdyrcd_numeric_wrapperClass))

typedef struct _yrcdyrcd_numeric_wrapper yrcdyrcd_numeric_wrapper;
typedef struct _yrcdyrcd_numeric_wrapperClass yrcdyrcd_numeric_wrapperClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
typedef struct _yrcdyrcd_numeric_wrapperPrivate yrcdyrcd_numeric_wrapperPrivate;

struct _yrcdyrcd_user {
	GObject parent_instance;
	yrcdyrcd_userPrivate * priv;
	gint64 epoch;
	gchar* ip;
	gchar* host;
	GeeHashMap* user_chanels;
};

struct _yrcdyrcd_userClass {
	GObjectClass parent_class;
};

struct _yrcdyrcd_userPrivate {
	GSocketConnection* _sock;
	GDataInputStream* _dis;
	GDataOutputStream* _dos;
	yrcdyrcd_server* _server;
	gint _id;
	gint64 time_last_rcv;
	gchar* _nick;
	gchar* _ident;
	gchar* _realname;
	gboolean _user_set;
};

struct _yrcdyrcd_server {
	GObject parent_instance;
	yrcdyrcd_serverPrivate * priv;
	GeeHashMap* channellist;
	gint64 epoch;
	gint max_users;
	yrcdyrcd_numeric_wrapper* numeric_wrapper;
};

struct _yrcdyrcd_serverClass {
	GObjectClass parent_class;
};

struct _yrcdyrcd_numeric_wrapper {
	GObject parent_instance;
	yrcdyrcd_numeric_wrapperPrivate * priv;
	GeeHashMap* numerics;
};

struct _yrcdyrcd_numeric_wrapperClass {
	GObjectClass parent_class;
};


static gpointer yrcd_yrcd_user_parent_class = NULL;

GType yrcd_yrcd_user_get_type (void) G_GNUC_CONST;
GType yrcd_yrcd_channel_get_type (void) G_GNUC_CONST;
GType yrcd_yrcd_server_get_type (void) G_GNUC_CONST;
#define YRCD_YRCD_USER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), YRCD_TYPE_YRCD_USER, yrcdyrcd_userPrivate))
enum  {
	YRCD_YRCD_USER_DUMMY_PROPERTY,
	YRCD_YRCD_USER_SOCK,
	YRCD_YRCD_USER_DIS,
	YRCD_YRCD_USER_DOS,
	YRCD_YRCD_USER_SERVER,
	YRCD_YRCD_USER_ID,
	YRCD_YRCD_USER_NICK,
	YRCD_YRCD_USER_IDENT,
	YRCD_YRCD_USER_REALNAME,
	YRCD_YRCD_USER_USER_SET
};
yrcdyrcd_user* yrcd_yrcd_user_new (GSocketConnection* conn, yrcdyrcd_server* _server);
yrcdyrcd_user* yrcd_yrcd_user_construct (GType object_type, GSocketConnection* conn, yrcdyrcd_server* _server);
void yrcd_yrcd_user_set_sock (yrcdyrcd_user* self, GSocketConnection* value);
void yrcd_yrcd_user_set_server (yrcdyrcd_user* self, yrcdyrcd_server* value);
gchar* yrcd_yrcd_user_get_ip (yrcdyrcd_user* self);
GSocketConnection* yrcd_yrcd_user_get_sock (yrcdyrcd_user* self);
void yrcd_yrcd_user_set_dis (yrcdyrcd_user* self, GDataInputStream* value);
void yrcd_yrcd_user_set_dos (yrcdyrcd_user* self, GDataOutputStream* value);
yrcdyrcd_server* yrcd_yrcd_user_get_server (yrcdyrcd_user* self);
gint yrcd_yrcd_server_new_userid (yrcdyrcd_server* self);
void yrcd_yrcd_user_set_id (yrcdyrcd_user* self, gint value);
gchar* yrcd_yrcd_user_get_host (yrcdyrcd_user* self);
void yrcd_yrcd_server_log (yrcdyrcd_server* self, const gchar* msg);
gint yrcd_yrcd_user_get_id (yrcdyrcd_user* self);
gboolean yrcd_yrcd_user_isnickset (yrcdyrcd_user* self);
const gchar* yrcd_yrcd_user_get_nick (yrcdyrcd_user* self);
void yrcd_yrcd_user_quit (yrcdyrcd_user* self, const gchar* msg);
void yrcd_yrcd_server_remove_user (yrcdyrcd_server* self, gint id);
void yrcd_yrcd_user_join (yrcdyrcd_user* self, yrcdyrcd_channel* chan);
gboolean yrcd_yrcd_channel_add_user (yrcdyrcd_channel* self, yrcdyrcd_user* user);
gint yrcd_yrcd_channel_get_cid (yrcdyrcd_channel* self);
void yrcd_yrcd_user_change_nick (yrcdyrcd_user* self, gchar** args, int args_length1);
void yrcd_yrcd_user_fire_numeric (yrcdyrcd_user* self, gint numeric, ...);
#define YRCD_ERR_NONICKNAMEGIVEN 431
yrcdyrcd_user* yrcd_yrcd_server_get_user_by_nick (yrcdyrcd_server* self, const gchar* nicktocheck);
#define YRCD_ERR_NICKNAMEINUSE 433
#define YRCD_ERR_ERRONEOUSNICKNAME 432
void yrcd_yrcd_user_set_nick (yrcdyrcd_user* self, const gchar* value);
gboolean yrcd_yrcd_user_get_user_set (yrcdyrcd_user* self);
void yrcd_yrcd_user_reg_finished (yrcdyrcd_user* self);
void yrcd_yrcd_user_user_reg (yrcdyrcd_user* self, gchar** args, int args_length1);
void yrcd_yrcd_user_set_ident (yrcdyrcd_user* self, const gchar* value);
void yrcd_yrcd_user_set_realname (yrcdyrcd_user* self, const gchar* value);
void yrcd_yrcd_user_set_user_set (yrcdyrcd_user* self, gboolean value);
gchar* yrcd_yrcd_user_get_hostmask (yrcdyrcd_user* self);
const gchar* yrcd_yrcd_user_get_realname (yrcdyrcd_user* self);
#define YRCD_RPL_WELCOME 001
const gchar* yrcd_yrcd_user_get_ident (yrcdyrcd_user* self);
#define YRCD_RPL_YOURHOST 002
#define YRCD_YRCD_CONSTANTS_sname "test.net.local"
#define YRCD_YRCD_CONSTANTS_software "yrcd"
#define YRCD_YRCD_CONSTANTS_version "0.1"
#define YRCD_RPL_CREATED 003
gchar* yrcd_yrcd_server_ut_to_utc (yrcdyrcd_server* self, gint64 ut);
GType yrcd_yrcd_numeric_wrapper_get_type (void) G_GNUC_CONST;
#define YRCD_RPL_MYINFO 004
void yrcd_yrcd_user_update_timestamp (yrcdyrcd_user* self);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
void yrcd_yrcd_user_send_line (yrcdyrcd_user* self, const gchar* msg);
GDataOutputStream* yrcd_yrcd_user_get_dos (yrcdyrcd_user* self);
GDataInputStream* yrcd_yrcd_user_get_dis (yrcdyrcd_user* self);
static void yrcd_yrcd_user_finalize (GObject* obj);
static void _vala_yrcd_yrcd_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_yrcd_yrcd_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);

extern const gchar* YRCD_YRCD_CONSTANTS_forbidden_nick_chars[6];

yrcdyrcd_user* yrcd_yrcd_user_construct (GType object_type, GSocketConnection* conn, yrcdyrcd_server* _server) {
	yrcdyrcd_user * self = NULL;
	GSocketConnection* _tmp0_ = NULL;
	yrcdyrcd_server* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GSocketConnection* _tmp3_ = NULL;
	GInputStream* _tmp4_ = NULL;
	GInputStream* _tmp5_ = NULL;
	GDataInputStream* _tmp6_ = NULL;
	GDataInputStream* _tmp7_ = NULL;
	GSocketConnection* _tmp8_ = NULL;
	GOutputStream* _tmp9_ = NULL;
	GOutputStream* _tmp10_ = NULL;
	GDataOutputStream* _tmp11_ = NULL;
	GDataOutputStream* _tmp12_ = NULL;
	yrcdyrcd_server* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	GDateTime* _tmp15_ = NULL;
	GDateTime* _tmp16_ = NULL;
	gint64 _tmp17_ = 0LL;
	gchar* _tmp18_ = NULL;
	yrcdyrcd_server* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (conn != NULL, NULL);
	g_return_val_if_fail (_server != NULL, NULL);
	self = (yrcdyrcd_user*) g_object_new (object_type, NULL);
	_tmp0_ = conn;
	yrcd_yrcd_user_set_sock (self, _tmp0_);
	_tmp1_ = _server;
	yrcd_yrcd_user_set_server (self, _tmp1_);
	_tmp2_ = yrcd_yrcd_user_get_ip (self);
	_g_free0 (self->ip);
	self->ip = _tmp2_;
	_tmp3_ = self->priv->_sock;
	_tmp4_ = g_io_stream_get_input_stream ((GIOStream*) _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_data_input_stream_new (_tmp5_);
	_tmp7_ = _tmp6_;
	yrcd_yrcd_user_set_dis (self, _tmp7_);
	_g_object_unref0 (_tmp7_);
	_tmp8_ = self->priv->_sock;
	_tmp9_ = g_io_stream_get_output_stream ((GIOStream*) _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_data_output_stream_new (_tmp10_);
	_tmp12_ = _tmp11_;
	yrcd_yrcd_user_set_dos (self, _tmp12_);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = self->priv->_server;
	_tmp14_ = yrcd_yrcd_server_new_userid (_tmp13_);
	yrcd_yrcd_user_set_id (self, _tmp14_);
	_tmp15_ = g_date_time_new_now_utc ();
	_tmp16_ = _tmp15_;
	_tmp17_ = g_date_time_to_unix (_tmp16_);
	self->epoch = _tmp17_;
	_g_date_time_unref0 (_tmp16_);
	_tmp18_ = yrcd_yrcd_user_get_host (self);
	_g_free0 (self->host);
	self->host = _tmp18_;
	_tmp19_ = self->priv->_server;
	_tmp20_ = self->host;
	_tmp21_ = self->priv->_id;
	_tmp22_ = g_strdup_printf ("User connected from %s with ID %d", _tmp20_, _tmp21_);
	_tmp23_ = _tmp22_;
	yrcd_yrcd_server_log (_tmp19_, _tmp23_);
	_g_free0 (_tmp23_);
	return self;
}


yrcdyrcd_user* yrcd_yrcd_user_new (GSocketConnection* conn, yrcdyrcd_server* _server) {
	return yrcd_yrcd_user_construct (YRCD_TYPE_YRCD_USER, conn, _server);
}


gboolean yrcd_yrcd_user_isnickset (yrcdyrcd_user* self) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_nick;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		const gchar* _tmp1_ = NULL;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		_tmp1_ = self->priv->_nick;
		_tmp2_ = strlen (_tmp1_);
		_tmp3_ = _tmp2_;
		if (_tmp3_ > 0) {
			result = TRUE;
			return result;
		} else {
			result = FALSE;
			return result;
		}
	}
}


gchar* yrcd_yrcd_user_get_ip (yrcdyrcd_user* self) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	{
		GSocketAddress* _tmp0_ = NULL;
		GSocketConnection* _tmp1_ = NULL;
		GSocketAddress* _tmp2_ = NULL;
		GInetSocketAddress* inetsockaddr = NULL;
		GSocketAddress* _tmp3_ = NULL;
		GInetSocketAddress* _tmp4_ = NULL;
		gchar* ip = NULL;
		GInetSocketAddress* _tmp5_ = NULL;
		GInetAddress* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		_tmp1_ = self->priv->_sock;
		_tmp2_ = g_socket_connection_get_remote_address (_tmp1_, &_inner_error_);
		_tmp0_ = _tmp2_;
		if (_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
		_tmp3_ = _tmp0_;
		_tmp0_ = NULL;
		_tmp4_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, g_inet_socket_address_get_type ()) ? ((GInetSocketAddress*) _tmp3_) : NULL;
		if (_tmp4_ == NULL) {
			_g_object_unref0 (_tmp3_);
		}
		inetsockaddr = _tmp4_;
		_tmp5_ = inetsockaddr;
		_tmp6_ = g_inet_socket_address_get_address (_tmp5_);
		_tmp7_ = g_inet_address_to_string (_tmp6_);
		ip = _tmp7_;
		result = ip;
		_g_object_unref0 (inetsockaddr);
		_g_object_unref0 (_tmp0_);
		return result;
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		yrcdyrcd_server* _tmp8_ = NULL;
		GError* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp8_ = self->priv->_server;
		_tmp9_ = e;
		_tmp10_ = _tmp9_->message;
		_tmp11_ = g_strdup_printf ("Error getting user ip: %s", _tmp10_);
		_tmp12_ = _tmp11_;
		yrcd_yrcd_server_log (_tmp8_, _tmp12_);
		_g_free0 (_tmp12_);
		_tmp13_ = g_strdup ("unknown");
		result = _tmp13_;
		_g_error_free0 (e);
		return result;
	}
	__finally2:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void yrcd_yrcd_user_quit (yrcdyrcd_user* self, const gchar* msg) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GSocketConnection* _tmp0_ = NULL;
		GSocket* _tmp1_ = NULL;
		yrcdyrcd_server* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		_tmp0_ = self->priv->_sock;
		_tmp1_ = g_socket_connection_get_socket (_tmp0_);
		g_socket_close (_tmp1_, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch3_g_error;
		}
		_tmp2_ = self->priv->_server;
		_tmp3_ = self->priv->_id;
		yrcd_yrcd_server_remove_user (_tmp2_, _tmp3_);
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		yrcdyrcd_server* _tmp4_ = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = self->priv->_server;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		_tmp7_ = g_strdup_printf ("Error closing socket: %s", _tmp6_);
		_tmp8_ = _tmp7_;
		yrcd_yrcd_server_log (_tmp4_, _tmp8_);
		_g_free0 (_tmp8_);
		_g_error_free0 (e);
	}
	__finally3:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void yrcd_yrcd_user_join (yrcdyrcd_user* self, yrcdyrcd_channel* chan) {
	yrcdyrcd_channel* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (chan != NULL);
	_tmp0_ = chan;
	_tmp1_ = yrcd_yrcd_channel_add_user (_tmp0_, self);
	if (_tmp1_) {
		GeeHashMap* _tmp2_ = NULL;
		yrcdyrcd_channel* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		yrcdyrcd_channel* _tmp6_ = NULL;
		_tmp2_ = self->user_chanels;
		_tmp3_ = chan;
		_tmp4_ = yrcd_yrcd_channel_get_cid (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = chan;
		gee_abstract_map_set ((GeeAbstractMap*) _tmp2_, (gpointer) ((gintptr) _tmp5_), _tmp6_);
	}
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


void yrcd_yrcd_user_change_nick (yrcdyrcd_user* self, gchar** args, int args_length1) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	yrcdyrcd_server* _tmp5_ = NULL;
	gchar** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	const gchar* _tmp7_ = NULL;
	yrcdyrcd_user* _tmp8_ = NULL;
	yrcdyrcd_user* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	gchar* oldnick = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	const gchar* _tmp23_ = NULL;
	gboolean _tmp24_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	if (_tmp0__length1 < 2) {
		yrcdyrcd_server* _tmp1_ = NULL;
		gint _tmp2_ = 0;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		_tmp1_ = self->priv->_server;
		_tmp2_ = self->priv->_id;
		_tmp3_ = g_strdup_printf ("User %d attempted NICK with invalid arguments", _tmp2_);
		_tmp4_ = _tmp3_;
		yrcd_yrcd_server_log (_tmp1_, _tmp4_);
		_g_free0 (_tmp4_);
		yrcd_yrcd_user_fire_numeric (self, YRCD_ERR_NONICKNAMEGIVEN, NULL);
		return;
	}
	_tmp5_ = self->priv->_server;
	_tmp6_ = args;
	_tmp6__length1 = args_length1;
	_tmp7_ = _tmp6_[1];
	_tmp8_ = yrcd_yrcd_server_get_user_by_nick (_tmp5_, _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = _tmp9_ != NULL;
	_g_object_unref0 (_tmp9_);
	if (_tmp10_) {
		gchar** _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		const gchar* _tmp12_ = NULL;
		_tmp11_ = args;
		_tmp11__length1 = args_length1;
		_tmp12_ = _tmp11_[1];
		yrcd_yrcd_user_fire_numeric (self, YRCD_ERR_NICKNAMEINUSE, _tmp12_, NULL);
		return;
	}
	{
		const gchar** k_collection = NULL;
		gint k_collection_length1 = 0;
		gint _k_collection_size_ = 0;
		gint k_it = 0;
		k_collection = YRCD_YRCD_CONSTANTS_forbidden_nick_chars;
		k_collection_length1 = G_N_ELEMENTS (YRCD_YRCD_CONSTANTS_forbidden_nick_chars);
		for (k_it = 0; k_it < G_N_ELEMENTS (YRCD_YRCD_CONSTANTS_forbidden_nick_chars); k_it = k_it + 1) {
			gchar* _tmp13_ = NULL;
			gchar* k = NULL;
			_tmp13_ = g_strdup (k_collection[k_it]);
			k = _tmp13_;
			{
				gchar** _tmp14_ = NULL;
				gint _tmp14__length1 = 0;
				const gchar* _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				gboolean _tmp17_ = FALSE;
				_tmp14_ = args;
				_tmp14__length1 = args_length1;
				_tmp15_ = _tmp14_[1];
				_tmp16_ = k;
				_tmp17_ = string_contains (_tmp15_, _tmp16_);
				if (_tmp17_) {
					gchar** _tmp18_ = NULL;
					gint _tmp18__length1 = 0;
					const gchar* _tmp19_ = NULL;
					_tmp18_ = args;
					_tmp18__length1 = args_length1;
					_tmp19_ = _tmp18_[1];
					yrcd_yrcd_user_fire_numeric (self, YRCD_ERR_ERRONEOUSNICKNAME, _tmp19_, NULL);
					_g_free0 (k);
					return;
				}
				_g_free0 (k);
			}
		}
	}
	_tmp20_ = self->priv->_nick;
	_tmp21_ = g_strdup (_tmp20_);
	oldnick = _tmp21_;
	_tmp22_ = args;
	_tmp22__length1 = args_length1;
	_tmp23_ = _tmp22_[1];
	yrcd_yrcd_user_set_nick (self, _tmp23_);
	_tmp24_ = yrcd_yrcd_user_isnickset (self);
	if (!_tmp24_) {
		yrcdyrcd_server* _tmp25_ = NULL;
		gint _tmp26_ = 0;
		const gchar* _tmp27_ = NULL;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gboolean _tmp30_ = FALSE;
		_tmp25_ = self->priv->_server;
		_tmp26_ = self->priv->_id;
		_tmp27_ = self->priv->_nick;
		_tmp28_ = g_strdup_printf ("User %d set nick to %s", _tmp26_, _tmp27_);
		_tmp29_ = _tmp28_;
		yrcd_yrcd_server_log (_tmp25_, _tmp29_);
		_g_free0 (_tmp29_);
		_tmp30_ = self->priv->_user_set;
		if (_tmp30_) {
			yrcd_yrcd_user_reg_finished (self);
		}
	} else {
		yrcdyrcd_server* _tmp31_ = NULL;
		gint _tmp32_ = 0;
		const gchar* _tmp33_ = NULL;
		const gchar* _tmp34_ = NULL;
		gchar* _tmp35_ = NULL;
		gchar* _tmp36_ = NULL;
		_tmp31_ = self->priv->_server;
		_tmp32_ = self->priv->_id;
		_tmp33_ = oldnick;
		_tmp34_ = self->priv->_nick;
		_tmp35_ = g_strdup_printf ("User %d changed nick from %s to %s", _tmp32_, _tmp33_, _tmp34_);
		_tmp36_ = _tmp35_;
		yrcd_yrcd_server_log (_tmp31_, _tmp36_);
		_g_free0 (_tmp36_);
	}
	_g_free0 (oldnick);
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch4_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) (-1), 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch4_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally4;
	__catch4_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally4:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


void yrcd_yrcd_user_user_reg (yrcdyrcd_user* self, gchar** args, int args_length1) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_user_set;
	if (!_tmp0_) {
		gchar** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		const gchar* _tmp2_ = NULL;
		gchar** _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		const gchar* _tmp4_ = NULL;
		gboolean _tmp5_ = FALSE;
		gint i = 0;
		GString* builder = NULL;
		GString* _tmp11_ = NULL;
		GString* _tmp21_ = NULL;
		const gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		gboolean _tmp25_ = FALSE;
		_tmp1_ = args;
		_tmp1__length1 = args_length1;
		_tmp2_ = _tmp1_[1];
		yrcd_yrcd_user_set_ident (self, _tmp2_);
		_tmp3_ = args;
		_tmp3__length1 = args_length1;
		_tmp4_ = _tmp3_[4];
		_tmp5_ = g_str_has_prefix (_tmp4_, ":");
		if (_tmp5_) {
			gchar** _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			gchar** _tmp7_ = NULL;
			gint _tmp7__length1 = 0;
			const gchar* _tmp8_ = NULL;
			gchar* _tmp9_ = NULL;
			gchar* _tmp10_ = NULL;
			_tmp6_ = args;
			_tmp6__length1 = args_length1;
			_tmp7_ = args;
			_tmp7__length1 = args_length1;
			_tmp8_ = _tmp7_[4];
			_tmp9_ = string_replace (_tmp8_, ":", "");
			_g_free0 (_tmp6_[4]);
			_tmp6_[4] = _tmp9_;
			_tmp10_ = _tmp6_[4];
		}
		_tmp11_ = g_string_new ("");
		builder = _tmp11_;
		{
			gboolean _tmp12_ = FALSE;
			i = 4;
			_tmp12_ = TRUE;
			while (TRUE) {
				gint _tmp14_ = 0;
				gchar** _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				GString* _tmp16_ = NULL;
				gchar** _tmp17_ = NULL;
				gint _tmp17__length1 = 0;
				gint _tmp18_ = 0;
				const gchar* _tmp19_ = NULL;
				GString* _tmp20_ = NULL;
				if (!_tmp12_) {
					gint _tmp13_ = 0;
					_tmp13_ = i;
					i = _tmp13_ + 1;
				}
				_tmp12_ = FALSE;
				_tmp14_ = i;
				_tmp15_ = args;
				_tmp15__length1 = args_length1;
				if (!(_tmp14_ < _tmp15__length1)) {
					break;
				}
				_tmp16_ = builder;
				_tmp17_ = args;
				_tmp17__length1 = args_length1;
				_tmp18_ = i;
				_tmp19_ = _tmp17_[_tmp18_];
				g_string_append (_tmp16_, _tmp19_);
				_tmp20_ = builder;
				g_string_append (_tmp20_, " ");
			}
		}
		_tmp21_ = builder;
		_tmp22_ = _tmp21_->str;
		_tmp23_ = string_strip (_tmp22_);
		_tmp24_ = _tmp23_;
		yrcd_yrcd_user_set_realname (self, _tmp24_);
		_g_free0 (_tmp24_);
		yrcd_yrcd_user_set_user_set (self, TRUE);
		_tmp25_ = yrcd_yrcd_user_isnickset (self);
		if (_tmp25_) {
			yrcd_yrcd_user_reg_finished (self);
		}
		_g_string_free0 (builder);
	} else {
		yrcdyrcd_server* _tmp26_ = NULL;
		gint _tmp27_ = 0;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		_tmp26_ = self->priv->_server;
		_tmp27_ = self->priv->_id;
		_tmp28_ = g_strdup_printf ("User %d attempted user registration while already registered", _tmp27_);
		_tmp29_ = _tmp28_;
		yrcd_yrcd_server_log (_tmp26_, _tmp29_);
		_g_free0 (_tmp29_);
		yrcd_yrcd_user_fire_numeric (self, 462, NULL);
	}
}


void yrcd_yrcd_user_reg_finished (yrcdyrcd_user* self) {
	yrcdyrcd_server* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	yrcdyrcd_server* _tmp10_ = NULL;
	yrcdyrcd_server* _tmp11_ = NULL;
	gint64 _tmp12_ = 0LL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_server;
	_tmp1_ = self->priv->_id;
	_tmp2_ = yrcd_yrcd_user_get_hostmask (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = self->priv->_realname;
	_tmp5_ = g_strdup_printf ("User %d finished registration with mask %s and realname %s", _tmp1_, _tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	yrcd_yrcd_server_log (_tmp0_, _tmp6_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp3_);
	_tmp7_ = self->priv->_nick;
	_tmp8_ = self->priv->_ident;
	_tmp9_ = self->host;
	yrcd_yrcd_user_fire_numeric (self, YRCD_RPL_WELCOME, _tmp7_, _tmp8_, _tmp9_, NULL);
	yrcd_yrcd_user_fire_numeric (self, YRCD_RPL_YOURHOST, YRCD_YRCD_CONSTANTS_sname, YRCD_YRCD_CONSTANTS_software, YRCD_YRCD_CONSTANTS_version, NULL);
	_tmp10_ = self->priv->_server;
	_tmp11_ = self->priv->_server;
	_tmp12_ = _tmp11_->epoch;
	_tmp13_ = yrcd_yrcd_server_ut_to_utc (_tmp10_, _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strdup_printf ("%s", _tmp14_);
	_tmp16_ = _tmp15_;
	yrcd_yrcd_user_fire_numeric (self, YRCD_RPL_CREATED, _tmp16_, NULL);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	yrcd_yrcd_user_fire_numeric (self, YRCD_RPL_MYINFO, YRCD_YRCD_CONSTANTS_sname, YRCD_YRCD_CONSTANTS_version, "", "", NULL);
}


void yrcd_yrcd_user_update_timestamp (yrcdyrcd_user* self) {
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	gint64 _tmp2_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_utc ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_date_time_to_unix (_tmp1_);
	self->priv->time_last_rcv = _tmp2_;
	_g_date_time_unref0 (_tmp1_);
}


gchar* yrcd_yrcd_user_get_hostmask (yrcdyrcd_user* self) {
	gchar* result = NULL;
	gchar* hm = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_nick;
	_tmp1_ = g_strconcat (_tmp0_, "!", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->_ident;
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, "@", NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = self->host;
	_tmp9_ = g_strconcat (_tmp7_, _tmp8_, NULL);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	hm = _tmp10_;
	result = hm;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


gchar* yrcd_yrcd_user_get_host (yrcdyrcd_user* self) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	{
		GInetAddress* address = NULL;
		const gchar* _tmp0_ = NULL;
		GInetAddress* _tmp1_ = NULL;
		GResolver* resolver = NULL;
		GResolver* _tmp2_ = NULL;
		gchar* hostname = NULL;
		GResolver* _tmp3_ = NULL;
		GInetAddress* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GList* addresses = NULL;
		GResolver* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		GList* _tmp8_ = NULL;
		gboolean match = FALSE;
		GList* _tmp9_ = NULL;
		gboolean _tmp16_ = FALSE;
		_tmp0_ = self->ip;
		_tmp1_ = g_inet_address_new_from_string (_tmp0_);
		address = _tmp1_;
		_tmp2_ = g_resolver_get_default ();
		resolver = _tmp2_;
		_tmp3_ = resolver;
		_tmp4_ = address;
		_tmp5_ = g_resolver_lookup_by_address (_tmp3_, _tmp4_, NULL, &_inner_error_);
		hostname = _tmp5_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (resolver);
			_g_object_unref0 (address);
			goto __catch5_g_error;
		}
		_tmp6_ = resolver;
		_tmp7_ = hostname;
		_tmp8_ = g_resolver_lookup_by_name (_tmp6_, _tmp7_, NULL, &_inner_error_);
		addresses = _tmp8_;
		if (_inner_error_ != NULL) {
			_g_free0 (hostname);
			_g_object_unref0 (resolver);
			_g_object_unref0 (address);
			goto __catch5_g_error;
		}
		match = FALSE;
		_tmp9_ = addresses;
		{
			GList* k_collection = NULL;
			GList* k_it = NULL;
			k_collection = _tmp9_;
			for (k_it = k_collection; k_it != NULL; k_it = k_it->next) {
				GInetAddress* _tmp10_ = NULL;
				GInetAddress* k = NULL;
				_tmp10_ = _g_object_ref0 ((GInetAddress*) k_it->data);
				k = _tmp10_;
				{
					GInetAddress* _tmp11_ = NULL;
					gchar* _tmp12_ = NULL;
					gchar* _tmp13_ = NULL;
					const gchar* _tmp14_ = NULL;
					gboolean _tmp15_ = FALSE;
					_tmp11_ = k;
					_tmp12_ = g_inet_address_to_string (_tmp11_);
					_tmp13_ = _tmp12_;
					_tmp14_ = self->ip;
					_tmp15_ = g_strcmp0 (_tmp13_, _tmp14_) == 0;
					_g_free0 (_tmp13_);
					if (_tmp15_) {
						match = TRUE;
					}
					_g_object_unref0 (k);
				}
			}
		}
		_tmp16_ = match;
		if (!_tmp16_) {
			const gchar* _tmp17_ = NULL;
			gchar* _tmp18_ = NULL;
			_tmp17_ = self->ip;
			_tmp18_ = g_strdup (_tmp17_);
			_g_free0 (hostname);
			hostname = _tmp18_;
		}
		result = hostname;
		__g_list_free__g_object_unref0_0 (addresses);
		_g_object_unref0 (resolver);
		_g_object_unref0 (address);
		return result;
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		yrcdyrcd_server* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		const gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		const gchar* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp19_ = self->priv->_server;
		_tmp20_ = self->priv->_id;
		_tmp21_ = self->ip;
		_tmp22_ = g_strdup_printf ("Error resolving user %d IP %s", _tmp20_, _tmp21_);
		_tmp23_ = _tmp22_;
		yrcd_yrcd_server_log (_tmp19_, _tmp23_);
		_g_free0 (_tmp23_);
		_tmp24_ = self->ip;
		_tmp25_ = g_strdup (_tmp24_);
		result = _tmp25_;
		_g_error_free0 (e);
		return result;
	}
	__finally5:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void yrcd_yrcd_user_send_line (yrcdyrcd_user* self, const gchar* msg) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (msg != NULL);
	{
		GDataOutputStream* _tmp0_ = NULL;
		const gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		_tmp0_ = self->priv->_dos;
		_tmp1_ = msg;
		_tmp2_ = g_strdup_printf ("%s\n", _tmp1_);
		_tmp3_ = _tmp2_;
		g_data_output_stream_put_string (_tmp0_, _tmp3_, NULL, &_inner_error_);
		_g_free0 (_tmp3_);
		if (_inner_error_ != NULL) {
			goto __catch6_g_error;
		}
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		yrcdyrcd_server* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = self->priv->_server;
		_tmp5_ = self->priv->_id;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		_tmp8_ = g_strdup_printf ("Error sending message to UID %d : %s", _tmp5_, _tmp7_);
		_tmp9_ = _tmp8_;
		yrcd_yrcd_server_log (_tmp4_, _tmp9_);
		_g_free0 (_tmp9_);
		_g_error_free0 (e);
	}
	__finally6:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void yrcd_yrcd_user_fire_numeric (yrcdyrcd_user* self, gint numeric, ...) {
	va_list args = {0};
	gchar* msg = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* msg2 = NULL;
	yrcdyrcd_server* _tmp3_ = NULL;
	yrcdyrcd_numeric_wrapper* _tmp4_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gpointer _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	g_return_if_fail (self != NULL);
	va_start (args, numeric);
	_tmp0_ = numeric;
	_tmp1_ = self->priv->_nick;
	_tmp2_ = g_strdup_printf (":%s %.3d %s :", YRCD_YRCD_CONSTANTS_sname, _tmp0_, _tmp1_);
	msg = _tmp2_;
	_tmp3_ = self->priv->_server;
	_tmp4_ = _tmp3_->numeric_wrapper;
	_tmp5_ = _tmp4_->numerics;
	_tmp6_ = numeric;
	_tmp7_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp5_, (gpointer) ((gintptr) _tmp6_));
	_tmp8_ = (gchar*) _tmp7_;
	_tmp9_ = g_strdup_vprintf (_tmp8_, args);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	msg2 = _tmp10_;
	_tmp11_ = msg;
	_tmp12_ = g_strconcat (_tmp11_, msg2, NULL);
	_g_free0 (msg);
	msg = _tmp12_;
	_tmp13_ = msg;
	yrcd_yrcd_user_send_line (self, _tmp13_);
	_g_free0 (msg2);
	_g_free0 (msg);
	va_end (args);
}


GSocketConnection* yrcd_yrcd_user_get_sock (yrcdyrcd_user* self) {
	GSocketConnection* result;
	GSocketConnection* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_sock;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_sock (yrcdyrcd_user* self, GSocketConnection* value) {
	GSocketConnection* _tmp0_ = NULL;
	GSocketConnection* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_sock);
	self->priv->_sock = _tmp1_;
	g_object_notify ((GObject *) self, "sock");
}


GDataInputStream* yrcd_yrcd_user_get_dis (yrcdyrcd_user* self) {
	GDataInputStream* result;
	GDataInputStream* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_dis;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_dis (yrcdyrcd_user* self, GDataInputStream* value) {
	GDataInputStream* _tmp0_ = NULL;
	GDataInputStream* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_dis);
	self->priv->_dis = _tmp1_;
	g_object_notify ((GObject *) self, "dis");
}


GDataOutputStream* yrcd_yrcd_user_get_dos (yrcdyrcd_user* self) {
	GDataOutputStream* result;
	GDataOutputStream* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_dos;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_dos (yrcdyrcd_user* self, GDataOutputStream* value) {
	GDataOutputStream* _tmp0_ = NULL;
	GDataOutputStream* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_dos);
	self->priv->_dos = _tmp1_;
	g_object_notify ((GObject *) self, "dos");
}


yrcdyrcd_server* yrcd_yrcd_user_get_server (yrcdyrcd_user* self) {
	yrcdyrcd_server* result;
	yrcdyrcd_server* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_server;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_server (yrcdyrcd_user* self, yrcdyrcd_server* value) {
	yrcdyrcd_server* _tmp0_ = NULL;
	yrcdyrcd_server* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_server);
	self->priv->_server = _tmp1_;
	g_object_notify ((GObject *) self, "server");
}


gint yrcd_yrcd_user_get_id (yrcdyrcd_user* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_id (yrcdyrcd_user* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_id = _tmp0_;
	g_object_notify ((GObject *) self, "id");
}


const gchar* yrcd_yrcd_user_get_nick (yrcdyrcd_user* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_nick;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_nick (yrcdyrcd_user* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_nick);
	self->priv->_nick = _tmp1_;
	g_object_notify ((GObject *) self, "nick");
}


const gchar* yrcd_yrcd_user_get_ident (yrcdyrcd_user* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_ident;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_ident (yrcdyrcd_user* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_ident);
	self->priv->_ident = _tmp1_;
	g_object_notify ((GObject *) self, "ident");
}


const gchar* yrcd_yrcd_user_get_realname (yrcdyrcd_user* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_realname;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_realname (yrcdyrcd_user* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_realname);
	self->priv->_realname = _tmp1_;
	g_object_notify ((GObject *) self, "realname");
}


gboolean yrcd_yrcd_user_get_user_set (yrcdyrcd_user* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_user_set;
	result = _tmp0_;
	return result;
}


void yrcd_yrcd_user_set_user_set (yrcdyrcd_user* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_user_set = _tmp0_;
	g_object_notify ((GObject *) self, "user-set");
}


static void yrcd_yrcd_user_class_init (yrcdyrcd_userClass * klass) {
	yrcd_yrcd_user_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (yrcdyrcd_userPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_yrcd_yrcd_user_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_yrcd_yrcd_user_set_property;
	G_OBJECT_CLASS (klass)->finalize = yrcd_yrcd_user_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_SOCK, g_param_spec_object ("sock", "sock", "sock", G_TYPE_SOCKET_CONNECTION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_DIS, g_param_spec_object ("dis", "dis", "dis", G_TYPE_DATA_INPUT_STREAM, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_DOS, g_param_spec_object ("dos", "dos", "dos", g_data_output_stream_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_SERVER, g_param_spec_object ("server", "server", "server", YRCD_TYPE_YRCD_SERVER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_ID, g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_NICK, g_param_spec_string ("nick", "nick", "nick", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_IDENT, g_param_spec_string ("ident", "ident", "ident", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_REALNAME, g_param_spec_string ("realname", "realname", "realname", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), YRCD_YRCD_USER_USER_SET, g_param_spec_boolean ("user-set", "user-set", "user-set", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void yrcd_yrcd_user_instance_init (yrcdyrcd_user * self) {
	GeeHashMap* _tmp0_ = NULL;
	self->priv = YRCD_YRCD_USER_GET_PRIVATE (self);
	_tmp0_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, YRCD_TYPE_YRCD_CHANNEL, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->user_chanels = _tmp0_;
}


static void yrcd_yrcd_user_finalize (GObject* obj) {
	yrcdyrcd_user * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_YRCD_USER, yrcdyrcd_user);
	_g_object_unref0 (self->priv->_sock);
	_g_object_unref0 (self->priv->_dis);
	_g_object_unref0 (self->priv->_dos);
	_g_object_unref0 (self->priv->_server);
	_g_free0 (self->priv->_nick);
	_g_free0 (self->priv->_ident);
	_g_free0 (self->priv->_realname);
	_g_free0 (self->ip);
	_g_free0 (self->host);
	_g_object_unref0 (self->user_chanels);
	G_OBJECT_CLASS (yrcd_yrcd_user_parent_class)->finalize (obj);
}


GType yrcd_yrcd_user_get_type (void) {
	static volatile gsize yrcd_yrcd_user_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_yrcd_user_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (yrcdyrcd_userClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_yrcd_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdyrcd_user), 0, (GInstanceInitFunc) yrcd_yrcd_user_instance_init, NULL };
		GType yrcd_yrcd_user_type_id;
		yrcd_yrcd_user_type_id = g_type_register_static (G_TYPE_OBJECT, "yrcdyrcd_user", &g_define_type_info, 0);
		g_once_init_leave (&yrcd_yrcd_user_type_id__volatile, yrcd_yrcd_user_type_id);
	}
	return yrcd_yrcd_user_type_id__volatile;
}


static void _vala_yrcd_yrcd_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	yrcdyrcd_user * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_USER, yrcdyrcd_user);
	switch (property_id) {
		case YRCD_YRCD_USER_SOCK:
		g_value_set_object (value, yrcd_yrcd_user_get_sock (self));
		break;
		case YRCD_YRCD_USER_DIS:
		g_value_set_object (value, yrcd_yrcd_user_get_dis (self));
		break;
		case YRCD_YRCD_USER_DOS:
		g_value_set_object (value, yrcd_yrcd_user_get_dos (self));
		break;
		case YRCD_YRCD_USER_SERVER:
		g_value_set_object (value, yrcd_yrcd_user_get_server (self));
		break;
		case YRCD_YRCD_USER_ID:
		g_value_set_int (value, yrcd_yrcd_user_get_id (self));
		break;
		case YRCD_YRCD_USER_NICK:
		g_value_set_string (value, yrcd_yrcd_user_get_nick (self));
		break;
		case YRCD_YRCD_USER_IDENT:
		g_value_set_string (value, yrcd_yrcd_user_get_ident (self));
		break;
		case YRCD_YRCD_USER_REALNAME:
		g_value_set_string (value, yrcd_yrcd_user_get_realname (self));
		break;
		case YRCD_YRCD_USER_USER_SET:
		g_value_set_boolean (value, yrcd_yrcd_user_get_user_set (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_yrcd_yrcd_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	yrcdyrcd_user * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, YRCD_TYPE_YRCD_USER, yrcdyrcd_user);
	switch (property_id) {
		case YRCD_YRCD_USER_SOCK:
		yrcd_yrcd_user_set_sock (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_DIS:
		yrcd_yrcd_user_set_dis (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_DOS:
		yrcd_yrcd_user_set_dos (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_SERVER:
		yrcd_yrcd_user_set_server (self, g_value_get_object (value));
		break;
		case YRCD_YRCD_USER_ID:
		yrcd_yrcd_user_set_id (self, g_value_get_int (value));
		break;
		case YRCD_YRCD_USER_NICK:
		yrcd_yrcd_user_set_nick (self, g_value_get_string (value));
		break;
		case YRCD_YRCD_USER_IDENT:
		yrcd_yrcd_user_set_ident (self, g_value_get_string (value));
		break;
		case YRCD_YRCD_USER_REALNAME:
		yrcd_yrcd_user_set_realname (self, g_value_get_string (value));
		break;
		case YRCD_YRCD_USER_USER_SET:
		yrcd_yrcd_user_set_user_set (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



