/* utils.c generated by valac 0.25.1, the Vala compiler
 * generated from utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))



gchar* yrcd_utils_secure_hash (const gchar* in, const gchar* salt);
gint64 yrcd_utils_now_unix (void);


gchar* yrcd_utils_secure_hash (const gchar* in, const gchar* salt) {
	gchar* result = NULL;
	GString* builder = NULL;
	GString* _tmp0_ = NULL;
	GString* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GString* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	GString* _tmp24_ = NULL;
	const gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	g_return_val_if_fail (in != NULL, NULL);
	g_return_val_if_fail (salt != NULL, NULL);
	_tmp0_ = g_string_new ("");
	builder = _tmp0_;
	_tmp1_ = builder;
	_tmp2_ = in;
	_tmp3_ = salt;
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, _tmp5_, (gsize) (-1));
	_tmp7_ = _tmp6_;
	g_string_append (_tmp1_, _tmp7_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	while (TRUE) {
		GString* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		const gchar* _tmp12_ = NULL;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		GString* _tmp15_ = NULL;
		GString* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		_tmp8_ = builder;
		_tmp9_ = _tmp8_->str;
		_tmp10_ = strlen (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp12_ = in;
		_tmp13_ = strlen (_tmp12_);
		_tmp14_ = _tmp13_;
		if (!(_tmp11_ < _tmp14_)) {
			break;
		}
		_tmp15_ = builder;
		_tmp16_ = builder;
		_tmp17_ = _tmp16_->str;
		_tmp18_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, _tmp17_, (gsize) (-1));
		_tmp19_ = _tmp18_;
		g_string_append (_tmp15_, _tmp19_);
		_g_free0 (_tmp19_);
	}
	_tmp20_ = builder;
	_tmp21_ = in;
	_tmp22_ = strlen (_tmp21_);
	_tmp23_ = _tmp22_;
	g_string_truncate (_tmp20_, (gsize) _tmp23_);
	_tmp24_ = builder;
	_tmp25_ = _tmp24_->str;
	_tmp26_ = g_strdup (_tmp25_);
	result = _tmp26_;
	_g_string_free0 (builder);
	return result;
}


gint64 yrcd_utils_now_unix (void) {
	gint64 result = 0LL;
	GDateTime* time = NULL;
	GDateTime* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	_tmp0_ = g_date_time_new_now_utc ();
	time = _tmp0_;
	_tmp1_ = g_date_time_to_unix (time);
	result = _tmp1_;
	_g_date_time_unref0 (time);
	return result;
}



