/* void.c generated by valac 0.24.0, the Vala compiler
 * generated from void.vala, do not modify */

/*...*/

#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define YRCD_TYPE_VOID_FUNC_DATA (yrcd_void_func_data_get_type ())
#define YRCD_VOID_FUNC_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_VOID_FUNC_DATA, yrcdVoidFuncData))
#define YRCD_VOID_FUNC_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_VOID_FUNC_DATA, yrcdVoidFuncDataClass))
#define YRCD_IS_VOID_FUNC_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_VOID_FUNC_DATA))
#define YRCD_IS_VOID_FUNC_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_VOID_FUNC_DATA))
#define YRCD_VOID_FUNC_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_VOID_FUNC_DATA, yrcdVoidFuncDataClass))

typedef struct _yrcdVoidFuncData yrcdVoidFuncData;
typedef struct _yrcdVoidFuncDataClass yrcdVoidFuncDataClass;
typedef struct _yrcdVoidFuncDataPrivate yrcdVoidFuncDataPrivate;
typedef struct _yrcdParamSpecVoidFuncData yrcdParamSpecVoidFuncData;

typedef void (*yrcdVoidFunc) (void* user_data);
struct _yrcdVoidFuncData {
	GTypeInstance parent_instance;
	volatile int ref_count;
	yrcdVoidFuncDataPrivate * priv;
	yrcdVoidFunc func;
	gpointer func_target;
	GDestroyNotify func_target_destroy_notify;
};

struct _yrcdVoidFuncDataClass {
	GTypeClass parent_class;
	void (*finalize) (yrcdVoidFuncData *self);
};

struct _yrcdParamSpecVoidFuncData {
	GParamSpec parent_instance;
};


static gpointer yrcd_void_func_data_parent_class = NULL;

gpointer yrcd_void_func_data_ref (gpointer instance);
void yrcd_void_func_data_unref (gpointer instance);
GParamSpec* yrcd_param_spec_void_func_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void yrcd_value_set_void_func_data (GValue* value, gpointer v_object);
void yrcd_value_take_void_func_data (GValue* value, gpointer v_object);
gpointer yrcd_value_get_void_func_data (const GValue* value);
GType yrcd_void_func_data_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_VOID_FUNC_DATA_DUMMY_PROPERTY
};
yrcdVoidFuncData* yrcd_void_func_data_new (yrcdVoidFunc func, void* func_target, GDestroyNotify func_target_destroy_notify);
yrcdVoidFuncData* yrcd_void_func_data_construct (GType object_type, yrcdVoidFunc func, void* func_target, GDestroyNotify func_target_destroy_notify);
static void yrcd_void_func_data_finalize (yrcdVoidFuncData* obj);


yrcdVoidFuncData* yrcd_void_func_data_construct (GType object_type, yrcdVoidFunc func, void* func_target, GDestroyNotify func_target_destroy_notify) {
	yrcdVoidFuncData* self = NULL;
	yrcdVoidFunc _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	GDestroyNotify _tmp0__target_destroy_notify = NULL;
	self = (yrcdVoidFuncData*) g_type_create_instance (object_type);
	_tmp0_ = func;
	_tmp0__target = func_target;
	_tmp0__target_destroy_notify = func_target_destroy_notify;
	func_target_destroy_notify = NULL;
	(self->func_target_destroy_notify == NULL) ? NULL : (self->func_target_destroy_notify (self->func_target), NULL);
	self->func = NULL;
	self->func_target = NULL;
	self->func_target_destroy_notify = NULL;
	self->func = _tmp0_;
	self->func_target = _tmp0__target;
	self->func_target_destroy_notify = _tmp0__target_destroy_notify;
	(func_target_destroy_notify == NULL) ? NULL : (func_target_destroy_notify (func_target), NULL);
	func = NULL;
	func_target = NULL;
	func_target_destroy_notify = NULL;
	return self;
}


yrcdVoidFuncData* yrcd_void_func_data_new (yrcdVoidFunc func, void* func_target, GDestroyNotify func_target_destroy_notify) {
	return yrcd_void_func_data_construct (YRCD_TYPE_VOID_FUNC_DATA, func, func_target, func_target_destroy_notify);
}


static void yrcd_value_void_func_data_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void yrcd_value_void_func_data_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		yrcd_void_func_data_unref (value->data[0].v_pointer);
	}
}


static void yrcd_value_void_func_data_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = yrcd_void_func_data_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer yrcd_value_void_func_data_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* yrcd_value_void_func_data_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		yrcdVoidFuncData* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = yrcd_void_func_data_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* yrcd_value_void_func_data_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	yrcdVoidFuncData** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = yrcd_void_func_data_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* yrcd_param_spec_void_func_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	yrcdParamSpecVoidFuncData* spec;
	g_return_val_if_fail (g_type_is_a (object_type, YRCD_TYPE_VOID_FUNC_DATA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer yrcd_value_get_void_func_data (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, YRCD_TYPE_VOID_FUNC_DATA), NULL);
	return value->data[0].v_pointer;
}


void yrcd_value_set_void_func_data (GValue* value, gpointer v_object) {
	yrcdVoidFuncData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, YRCD_TYPE_VOID_FUNC_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, YRCD_TYPE_VOID_FUNC_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		yrcd_void_func_data_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		yrcd_void_func_data_unref (old);
	}
}


void yrcd_value_take_void_func_data (GValue* value, gpointer v_object) {
	yrcdVoidFuncData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, YRCD_TYPE_VOID_FUNC_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, YRCD_TYPE_VOID_FUNC_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		yrcd_void_func_data_unref (old);
	}
}


static void yrcd_void_func_data_class_init (yrcdVoidFuncDataClass * klass) {
	yrcd_void_func_data_parent_class = g_type_class_peek_parent (klass);
	YRCD_VOID_FUNC_DATA_CLASS (klass)->finalize = yrcd_void_func_data_finalize;
}


static void yrcd_void_func_data_instance_init (yrcdVoidFuncData * self) {
	self->ref_count = 1;
}


static void yrcd_void_func_data_finalize (yrcdVoidFuncData* obj) {
	yrcdVoidFuncData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_VOID_FUNC_DATA, yrcdVoidFuncData);
	(self->func_target_destroy_notify == NULL) ? NULL : (self->func_target_destroy_notify (self->func_target), NULL);
	self->func = NULL;
	self->func_target = NULL;
	self->func_target_destroy_notify = NULL;
}


GType yrcd_void_func_data_get_type (void) {
	static volatile gsize yrcd_void_func_data_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_void_func_data_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { yrcd_value_void_func_data_init, yrcd_value_void_func_data_free_value, yrcd_value_void_func_data_copy_value, yrcd_value_void_func_data_peek_pointer, "p", yrcd_value_void_func_data_collect_value, "p", yrcd_value_void_func_data_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (yrcdVoidFuncDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_void_func_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdVoidFuncData), 0, (GInstanceInitFunc) yrcd_void_func_data_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType yrcd_void_func_data_type_id;
		yrcd_void_func_data_type_id = g_type_register_fundamental (g_type_fundamental_next (), "yrcdVoidFuncData", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&yrcd_void_func_data_type_id__volatile, yrcd_void_func_data_type_id);
	}
	return yrcd_void_func_data_type_id__volatile;
}


gpointer yrcd_void_func_data_ref (gpointer instance) {
	yrcdVoidFuncData* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void yrcd_void_func_data_unref (gpointer instance) {
	yrcdVoidFuncData* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		YRCD_VOID_FUNC_DATA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



