/* wrapper.c generated by valac 0.24.0, the Vala compiler
 * generated from wrapper.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define YRCD_TYPE_DELEGATE_WRAPPER (yrcd_delegate_wrapper_get_type ())
#define YRCD_DELEGATE_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), YRCD_TYPE_DELEGATE_WRAPPER, yrcdDelegateWrapper))
#define YRCD_DELEGATE_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), YRCD_TYPE_DELEGATE_WRAPPER, yrcdDelegateWrapperClass))
#define YRCD_IS_DELEGATE_WRAPPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), YRCD_TYPE_DELEGATE_WRAPPER))
#define YRCD_IS_DELEGATE_WRAPPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), YRCD_TYPE_DELEGATE_WRAPPER))
#define YRCD_DELEGATE_WRAPPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), YRCD_TYPE_DELEGATE_WRAPPER, yrcdDelegateWrapperClass))

typedef struct _yrcdDelegateWrapper yrcdDelegateWrapper;
typedef struct _yrcdDelegateWrapperClass yrcdDelegateWrapperClass;
typedef struct _yrcdDelegateWrapperPrivate yrcdDelegateWrapperPrivate;
typedef struct _yrcdParamSpecDelegateWrapper yrcdParamSpecDelegateWrapper;

typedef void (*yrcdDelegateWrapperDelegateType) (void* user_data);
struct _yrcdDelegateWrapper {
	GTypeInstance parent_instance;
	volatile int ref_count;
	yrcdDelegateWrapperPrivate * priv;
	yrcdDelegateWrapperDelegateType d;
	gpointer d_target;
	GDestroyNotify d_target_destroy_notify;
};

struct _yrcdDelegateWrapperClass {
	GTypeClass parent_class;
	void (*finalize) (yrcdDelegateWrapper *self);
};

struct _yrcdParamSpecDelegateWrapper {
	GParamSpec parent_instance;
};


static gpointer yrcd_delegate_wrapper_parent_class = NULL;

gpointer yrcd_delegate_wrapper_ref (gpointer instance);
void yrcd_delegate_wrapper_unref (gpointer instance);
GParamSpec* yrcd_param_spec_delegate_wrapper (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void yrcd_value_set_delegate_wrapper (GValue* value, gpointer v_object);
void yrcd_value_take_delegate_wrapper (GValue* value, gpointer v_object);
gpointer yrcd_value_get_delegate_wrapper (const GValue* value);
GType yrcd_delegate_wrapper_get_type (void) G_GNUC_CONST;
enum  {
	YRCD_DELEGATE_WRAPPER_DUMMY_PROPERTY
};
yrcdDelegateWrapper* yrcd_delegate_wrapper_new (yrcdDelegateWrapperDelegateType d, void* d_target);
yrcdDelegateWrapper* yrcd_delegate_wrapper_construct (GType object_type, yrcdDelegateWrapperDelegateType d, void* d_target);
static void yrcd_delegate_wrapper_finalize (yrcdDelegateWrapper* obj);


yrcdDelegateWrapper* yrcd_delegate_wrapper_construct (GType object_type, yrcdDelegateWrapperDelegateType d, void* d_target) {
	yrcdDelegateWrapper* self = NULL;
	yrcdDelegateWrapperDelegateType _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	self = (yrcdDelegateWrapper*) g_type_create_instance (object_type);
	_tmp0_ = d;
	_tmp0__target = d_target;
	(self->d_target_destroy_notify == NULL) ? NULL : (self->d_target_destroy_notify (self->d_target), NULL);
	self->d = NULL;
	self->d_target = NULL;
	self->d_target_destroy_notify = NULL;
	self->d = _tmp0_;
	self->d_target = _tmp0__target;
	self->d_target_destroy_notify = NULL;
	return self;
}


yrcdDelegateWrapper* yrcd_delegate_wrapper_new (yrcdDelegateWrapperDelegateType d, void* d_target) {
	return yrcd_delegate_wrapper_construct (YRCD_TYPE_DELEGATE_WRAPPER, d, d_target);
}


static void yrcd_value_delegate_wrapper_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void yrcd_value_delegate_wrapper_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		yrcd_delegate_wrapper_unref (value->data[0].v_pointer);
	}
}


static void yrcd_value_delegate_wrapper_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = yrcd_delegate_wrapper_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer yrcd_value_delegate_wrapper_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* yrcd_value_delegate_wrapper_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		yrcdDelegateWrapper* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = yrcd_delegate_wrapper_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* yrcd_value_delegate_wrapper_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	yrcdDelegateWrapper** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = yrcd_delegate_wrapper_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* yrcd_param_spec_delegate_wrapper (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	yrcdParamSpecDelegateWrapper* spec;
	g_return_val_if_fail (g_type_is_a (object_type, YRCD_TYPE_DELEGATE_WRAPPER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer yrcd_value_get_delegate_wrapper (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, YRCD_TYPE_DELEGATE_WRAPPER), NULL);
	return value->data[0].v_pointer;
}


void yrcd_value_set_delegate_wrapper (GValue* value, gpointer v_object) {
	yrcdDelegateWrapper* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, YRCD_TYPE_DELEGATE_WRAPPER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, YRCD_TYPE_DELEGATE_WRAPPER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		yrcd_delegate_wrapper_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		yrcd_delegate_wrapper_unref (old);
	}
}


void yrcd_value_take_delegate_wrapper (GValue* value, gpointer v_object) {
	yrcdDelegateWrapper* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, YRCD_TYPE_DELEGATE_WRAPPER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, YRCD_TYPE_DELEGATE_WRAPPER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		yrcd_delegate_wrapper_unref (old);
	}
}


static void yrcd_delegate_wrapper_class_init (yrcdDelegateWrapperClass * klass) {
	yrcd_delegate_wrapper_parent_class = g_type_class_peek_parent (klass);
	YRCD_DELEGATE_WRAPPER_CLASS (klass)->finalize = yrcd_delegate_wrapper_finalize;
}


static void yrcd_delegate_wrapper_instance_init (yrcdDelegateWrapper * self) {
	self->ref_count = 1;
}


static void yrcd_delegate_wrapper_finalize (yrcdDelegateWrapper* obj) {
	yrcdDelegateWrapper * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, YRCD_TYPE_DELEGATE_WRAPPER, yrcdDelegateWrapper);
	(self->d_target_destroy_notify == NULL) ? NULL : (self->d_target_destroy_notify (self->d_target), NULL);
	self->d = NULL;
	self->d_target = NULL;
	self->d_target_destroy_notify = NULL;
}


GType yrcd_delegate_wrapper_get_type (void) {
	static volatile gsize yrcd_delegate_wrapper_type_id__volatile = 0;
	if (g_once_init_enter (&yrcd_delegate_wrapper_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { yrcd_value_delegate_wrapper_init, yrcd_value_delegate_wrapper_free_value, yrcd_value_delegate_wrapper_copy_value, yrcd_value_delegate_wrapper_peek_pointer, "p", yrcd_value_delegate_wrapper_collect_value, "p", yrcd_value_delegate_wrapper_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (yrcdDelegateWrapperClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) yrcd_delegate_wrapper_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (yrcdDelegateWrapper), 0, (GInstanceInitFunc) yrcd_delegate_wrapper_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType yrcd_delegate_wrapper_type_id;
		yrcd_delegate_wrapper_type_id = g_type_register_fundamental (g_type_fundamental_next (), "yrcdDelegateWrapper", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&yrcd_delegate_wrapper_type_id__volatile, yrcd_delegate_wrapper_type_id);
	}
	return yrcd_delegate_wrapper_type_id__volatile;
}


gpointer yrcd_delegate_wrapper_ref (gpointer instance) {
	yrcdDelegateWrapper* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void yrcd_delegate_wrapper_unref (gpointer instance) {
	yrcdDelegateWrapper* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		YRCD_DELEGATE_WRAPPER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



